# Additional CLF-C02 practice questions (official exam domain IDs and weights in generate-questions.py).
# Tuple: domain, type, text, options, correct, explanation, docs

EXTENDED = [
    # --- Domain 1: Cloud Concepts (24%) ---
    ("cloud-concepts", "multiple-choice",
     "Which Well-Architected pillar focuses on minimizing the environmental impact of running cloud workloads?",
     [("a", "Sustainability"), ("b", "Security"), ("c", "Reliability"), ("d", "Performance Efficiency")], ["a"],
     "Sustainability focuses on energy efficiency and reducing waste in cloud architectures.",
     [("Sustainability pillar", "https://docs.aws.amazon.com/wellarchitected/latest/sustainability-pillar/sustainability-pillar.html")]),
    ("cloud-concepts", "multiple-choice",
     "Fault tolerance in the AWS Cloud is most closely associated with which concept?",
     [("a", "Single-AZ deployment"), ("b", "Designing for component failure without service interruption"),
      ("c", "Using one large instance"), ("d", "Disabling backups")], ["b"],
     "Fault-tolerant designs continue operating when components fail, often using redundancy across AZs.",
     [("Reliability pillar", "https://docs.aws.amazon.com/wellarchitected/latest/reliability-pillar/welcome.html")]),
    ("cloud-concepts", "multiple-response",
     "Which are characteristics of the AWS Cloud? (Select TWO.)",
     [("a", "Elasticity"), ("b", "Fixed physical server ownership by customers"), ("c", "Broad network access"),
      ("d", "Manual capacity planning only"), ("e", "Measured service")], ["a", "c", "e"],
     "NIST-style characteristics include on-demand self-service, broad network access, resource pooling, rapid elasticity, and measured service.",
     [("AWS Overview", "https://docs.aws.amazon.com/whitepapers/latest/aws-overview/")]),
    ("cloud-concepts", "multiple-choice",
     "AWS Service Catalog allows organizations to:",
     [("a", "Create and manage approved catalogs of IT services for users"), ("b", "Replace IAM policies"), ("c", "Monitor physical data centers"), ("d", "Ship Snowball devices")], ["a"],
     "Service Catalog helps govern which products users can deploy from approved templates.",
     [("AWS Service Catalog", "https://docs.aws.amazon.com/servicecatalog/latest/adminguide/introduction.html")]),
    ("cloud-concepts", "multiple-choice",
     "Which statement describes the AWS shared responsibility model?",
     [("a", "AWS is responsible for everything"), ("b", "Security and compliance are shared between AWS and the customer"),
      ("c", "Customers manage physical hardware"), ("d", "AWS manages guest operating systems on EC2")], ["b"],
     "AWS secures the cloud; customers secure what they run in the cloud.",
     [("Shared Responsibility", "https://aws.amazon.com/compliance/shared-responsibility-model/")]),
    ("cloud-concepts", "multiple-choice",
     "A company needs to run workloads with the lowest possible operational overhead for an unpredictable web app. Which approach aligns with cloud value?",
     [("a", "Buy data center hardware in advance"), ("b", "Use managed and serverless services"), ("c", "Avoid monitoring"), ("d", "Single server in one AZ")], ["b"],
     "Managed/serverless services reduce undifferentiated heavy lifting and scale with demand.",
     [("AWS Cloud Value", "https://aws.amazon.com/what-is-cloud-computing/")]),
    ("cloud-concepts", "multiple-choice",
     "Which AWS service provides a single sign-on experience to multiple AWS accounts and business applications?",
     [("a", "IAM Identity Center"), ("b", "Amazon Macie"), ("c", "AWS Batch"), ("d", "Amazon EBS")], ["a"],
     "IAM Identity Center (AWS SSO) centralizes access to accounts and SAML applications.",
     [("IAM Identity Center", "https://docs.aws.amazon.com/singlesignon/latest/userguide/what-is.html")]),
    ("cloud-concepts", "multiple-choice",
     "Disaster recovery strategies on AWS often use:",
     [("a", "Multiple Regions and backup services"), ("b", "A single laptop"), ("c", "Disabling snapshots"), ("d", "Removing IAM roles")], ["a"],
     "Cross-Region replication and backups support RTO/RPO goals for DR.",
     [("Disaster Recovery", "https://docs.aws.amazon.com/whitepapers/latest/disaster-recovery-workloads-on-aws/disaster-recovery-workloads-on-aws.html")]),
    ("cloud-concepts", "multiple-choice",
     "Which benefit describes trading upfront data center costs for pay-as-you-go pricing?",
     [("a", "Variable expense instead of capital expense"), ("b", "Unlimited free usage"), ("c", "No need for architecture"), ("d", "Elimination of all security")], ["a"],
     "Cloud converts CapEx to OpEx with consumption-based pricing.",
     [("Six advantages", "https://docs.aws.amazon.com/whitepapers/latest/aws-overview/six-advantages-of-cloud-computing.html")]),
    ("cloud-concepts", "multiple-choice",
     "The AWS Well-Architected Tool is used to:",
     [("a", "Review workloads against best practices"), ("b", "Replace CloudTrail"), ("c", "Register domains"), ("d", "Create EC2 AMIs only")], ["a"],
     "The tool helps document and improve architectures using the Well-Architected Framework.",
     [("Well-Architected Tool", "https://docs.aws.amazon.com/wellarchitected/latest/userguide/intro.html")]),
    ("cloud-concepts", "multiple-choice",
     "Which is an example of horizontal scaling?",
     [("a", "Adding more EC2 instances behind a load balancer"), ("b", "Upgrading to a larger instance size only"), ("c", "Using a single bigger disk"), ("d", "Disabling Auto Scaling")], ["a"],
     "Horizontal scaling adds instances; vertical scaling increases size of one instance.",
     [("AWS Auto Scaling", "https://docs.aws.amazon.com/autoscaling/ec2/userguide/what-is-amazon-ec2-auto-scaling.html")]),
    ("cloud-concepts", "multiple-choice",
     "AWS Local Zones are designed to:",
     [("a", "Place compute closer to end users in metro areas"), ("b", "Replace all Regions"), ("c", "Store IAM policies"), ("d", "Provide email hosting")], ["a"],
     "Local Zones extend AWS infrastructure closer to populations for low-latency workloads.",
     [("AWS Local Zones", "https://aws.amazon.com/about-aws/global-infrastructure/localzones/")]),
    ("cloud-concepts", "multiple-choice",
     "Which pillar emphasizes using computing resources efficiently and adapting to changing requirements?",
     [("a", "Performance Efficiency"), ("b", "Cost Optimization only"), ("c", "Sustainability only"), ("d", "None of the above")], ["a"],
     "Performance Efficiency focuses on efficient use of IT and computing resources.",
     [("Performance Efficiency", "https://docs.aws.amazon.com/wellarchitected/latest/performance-efficiency-pillar/welcome.html")]),
    ("cloud-concepts", "multiple-choice",
     "Hybrid cloud typically means:",
     [("a", "Combining on-premises infrastructure with AWS Cloud"), ("b", "Using only one Availability Zone"), ("c", "No VPN connectivity"), ("d", "Only SaaS products")], ["a"],
     "Hybrid connects existing data centers to AWS via VPN, Direct Connect, or Outposts.",
     [("Hybrid cloud", "https://aws.amazon.com/hybrid/")]),
    ("cloud-concepts", "multiple-choice",
     "Which AWS program helps partners deliver solutions to customers?",
     [("a", "AWS Partner Network (APN)"), ("b", "AWS Budgets"), ("c", "Amazon S3 Glacier"), ("d", "VPC Flow Logs")], ["a"],
     "APN includes consulting and technology partners that build on AWS.",
     [("AWS Partner Network", "https://aws.amazon.com/partners/")]),
    ("cloud-concepts", "multiple-choice",
     "AWS Wickr is categorized under which type of service at a high level?",
     [("a", "Secure enterprise communication"), ("b", "Object storage"), ("c", "Data warehouse"), ("d", "DNS")], ["a"],
     "Wickr provides encrypted messaging for enterprises (communications/collaboration category).",
     [("AWS Wickr", "https://aws.amazon.com/wickr/")]),
    ("cloud-concepts", "multiple-choice",
     "Which describes economies of scale on AWS?",
     [("a", "AWS aggregates usage to pass savings to customers"), ("b", "Each customer builds their own data centers"), ("c", "Pricing never changes"), ("d", "Only Enterprise accounts benefit")], ["a"],
     "Large-scale infrastructure allows AWS to offer competitive pay-as-you-go pricing.",
     [("AWS Pricing", "https://aws.amazon.com/pricing/")]),
    ("cloud-concepts", "multiple-response",
     "Which are pillars of the AWS Well-Architected Framework? (Select TWO.)",
     [("a", "Reliability"), ("b", "Procurement"), ("c", "Cost Optimization"), ("d", "Marketing"), ("e", "Security")], ["a", "c", "e"],
     "Six pillars: Operational Excellence, Security, Reliability, Performance Efficiency, Cost Optimization, Sustainability.",
     [("Well-Architected Framework", "https://docs.aws.amazon.com/wellarchitected/latest/framework/welcome.html")]),
    # --- Domain 2: Security and Compliance (30%) ---
    ("security-compliance", "multiple-choice",
     "Amazon Inspector is primarily used to:",
     [("a", "Scan workloads for software vulnerabilities"), ("b", "Register domain names"), ("c", "Create S3 buckets"), ("d", "Manage payroll")], ["a"],
     "Inspector assesses EC2 and container workloads for vulnerabilities.",
     [("Amazon Inspector", "https://docs.aws.amazon.com/inspector/latest/user/what-is-inspector.html")]),
    ("security-compliance", "multiple-choice",
     "Amazon Macie helps discover and protect:",
     [("a", "Sensitive data in Amazon S3"), ("b", "EC2 instance types"), ("c", "Route tables"), ("d", "IAM user names only")], ["a"],
     "Macie uses machine learning to find sensitive data such as PII in S3.",
     [("Amazon Macie", "https://docs.aws.amazon.com/macie/latest/user/what-is-macie.html")]),
    ("security-compliance", "multiple-choice",
     "AWS Secrets Manager is designed to:",
     [("a", "Rotate, manage, and retrieve secrets"), ("b", "Replace VPC"), ("c", "Host static websites"), ("d", "Provide GPS tracking")], ["a"],
     "Secrets Manager stores credentials and can automate rotation.",
     [("AWS Secrets Manager", "https://docs.aws.amazon.com/secretsmanager/latest/userguide/intro.html")]),
    ("security-compliance", "multiple-choice",
     "Which IAM entity is intended for applications and AWS services to call AWS APIs?",
     [("a", "IAM role"), ("b", "Root user for daily tasks"), ("c", "Public access keys in code repos"), ("d", "Billing contact")], ["a"],
     "Roles provide temporary credentials without embedding long-term keys.",
     [("IAM roles", "https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles.html")]),
    ("security-compliance", "multiple-choice",
     "AWS Certificate Manager (ACM) provides:",
     [("a", "SSL/TLS certificates for AWS services"), ("b", "Physical security badges"), ("c", "EC2 instance families"), ("d", "S3 lifecycle rules")], ["a"],
     "ACM provisions and manages public and private SSL/TLS certificates.",
     [("AWS Certificate Manager", "https://docs.aws.amazon.com/acm/latest/userguide/acm-overview.html")]),
    ("security-compliance", "multiple-choice",
     "Penetration testing of certain AWS services without prior approval is:",
     [("a", "Allowed for a defined list of services under AWS policy"), ("b", "Never allowed"), ("c", "Only for GovCloud"), ("d", "Managed by S3 only")], ["a"],
     "AWS has a policy describing permitted security testing on specific services.",
     [("Penetration testing", "https://aws.amazon.com/security/penetration-testing/")]),
    ("security-compliance", "multiple-response",
     "Which are customer responsibilities under the shared responsibility model? (Select TWO.)",
     [("a", "Encrypting customer data in S3 as needed"), ("b", "Physical security of data centers"), ("c", "Managing IAM access policies"), ("d", "Patching the hypervisor"), ("e", "Hardware maintenance")], ["a", "c"],
     "Customers manage data, identity, platform configuration, and application security in the cloud.",
     [("Shared Responsibility", "https://aws.amazon.com/compliance/shared-responsibility-model/")]),
    ("security-compliance", "multiple-choice",
     "AWS Audit Manager helps:",
     [("a", "Continuously audit AWS usage against controls"), ("b", "Replace CloudWatch"), ("c", "Ship Snowball"), ("d", "Create CloudFront distributions")], ["a"],
     "Audit Manager automates evidence collection for audits and compliance frameworks.",
     [("AWS Audit Manager", "https://docs.aws.amazon.com/audit-manager/latest/userguide/what-is.html")]),
    ("security-compliance", "multiple-choice",
     "IAM Access Analyzer helps identify:",
     [("a", "Resources shared with external entities"), ("b", "Lowest EC2 price"), ("c", "S3 object size"), ("d", "Domain expiration")], ["a"],
     "Access Analyzer finds unintended access from outside your account or organization.",
     [("IAM Access Analyzer", "https://docs.aws.amazon.com/IAM/latest/UserGuide/what-is-access-analyzer.html")]),
    ("security-compliance", "multiple-choice",
     "Which service aggregates security alerts from multiple AWS accounts?",
     [("a", "AWS Security Hub"), ("b", "Amazon Polly"), ("c", "AWS Amplify"), ("d", "Amazon Rekognition")], ["a"],
     "Security Hub collects findings from GuardDuty, Inspector, Macie, and partner tools.",
     [("AWS Security Hub", "https://docs.aws.amazon.com/securityhub/latest/userguide/what-is-securityhub.html")]),
    ("security-compliance", "multiple-choice",
     "Encryption of data in transit to S3 is commonly achieved using:",
     [("a", "HTTPS (TLS)"), ("b", "FTP without encryption"), ("c", "Plain HTTP only"), ("d", "Telnet")], ["a"],
     "Use TLS when accessing S3 via REST APIs or the console.",
     [("S3 security", "https://docs.aws.amazon.com/AmazonS3/latest/userguide/security-best-practices.html")]),
    ("security-compliance", "multiple-choice",
     "The AWS root user should be used:",
     [("a", "Only for tasks that require root credentials"), ("b", "For daily development"), ("c", "Shared across the team"), ("d", "Embedded in application code")], ["a"],
     "Create IAM users/roles for daily work; secure root with MFA and minimal use.",
     [("IAM root best practices", "https://docs.aws.amazon.com/IAM/latest/UserGuide/best-practices.html")]),
    ("security-compliance", "multiple-choice",
     "Amazon Cognito provides:",
     [("a", "User sign-up, sign-in, and access control for web and mobile apps"), ("b", "Block storage"), ("c", "Data warehouse ETL"), ("d", "Hardware VPN appliances")], ["a"],
     "Cognito handles user directories, federation, and OAuth/OIDC flows for apps.",
     [("Amazon Cognito", "https://docs.aws.amazon.com/cognito/latest/developerguide/what-is-amazon-cognito.html")]),
    ("security-compliance", "multiple-choice",
     "AWS Firewall Manager is used to:",
     [("a", "Centrally configure WAF rules across accounts"), ("b", "Replace IAM"), ("c", "Monitor billing only"), ("d", "Create RDS snapshots")], ["a"],
     "Firewall Manager applies AWS WAF and VPC security policies across an organization.",
     [("AWS Firewall Manager", "https://docs.aws.amazon.com/waf/latest/developerguide/fms-chapter.html")]),
    ("security-compliance", "multiple-choice",
     "Which protects against common DDoS attacks on CloudFront and Route 53 at no extra charge?",
     [("a", "AWS Shield Standard"), ("b", "AWS Shield Advanced only"), ("c", "Amazon S3"), ("d", "AWS Glue")], ["a"],
     "Shield Standard is automatically included for all customers.",
     [("AWS Shield", "https://docs.aws.amazon.com/waf/latest/developerguide/shield-chapter.html")]),
    ("security-compliance", "multiple-choice",
     "AWS CloudHSM provides:",
     [("a", "Hardware security modules you control"), ("b", "Free public Wi-Fi"), ("c", "DNS caching"), ("d", "Email filtering")], ["a"],
     "CloudHSM offers dedicated HSM instances for keys you manage.",
     [("AWS CloudHSM", "https://docs.aws.amazon.com/cloudhsm/latest/userguide/introduction.html")]),
    ("security-compliance", "multiple-choice",
     "Compliance reports for HIPAA, PCI, and similar frameworks are often accessed through:",
     [("a", "AWS Artifact"), ("b", "Amazon SNS"), ("c", "AWS Batch"), ("d", "Amazon Lightsail")], ["a"],
     "Artifact provides compliance documentation customers need for audits.",
     [("AWS Artifact", "https://docs.aws.amazon.com/artifact/latest/ug/what-is-aws-artifact.html")]),
    ("security-compliance", "multiple-choice",
     "A security group rule change is an example of:",
     [("a", "Security in the cloud (customer responsibility)"), ("b", "Physical security of AWS"), ("c", "Hypervisor patching by AWS"), ("d", "Global edge caching")], ["a"],
     "Customers configure security groups and NACLs for their VPC resources.",
     [("VPC security", "https://docs.aws.amazon.com/vpc/latest/userguide/VPC_Security.html")]),
    ("security-compliance", "multiple-choice",
     "AWS IAM policy evaluation logic includes:",
     [("a", "Explicit deny overrides allow"), ("b", "Deny is ignored"), ("c", "Root is denied always"), ("d", "S3 has no policies")], ["a"],
     "By default requests are denied; explicit allow grants access unless explicit deny exists.",
     [("Policy evaluation", "https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_evaluation-logic.html")]),
    ("security-compliance", "multiple-response",
     "Which services support encryption? (Select TWO.)",
     [("a", "Amazon S3"), ("b", "Amazon VPC Flow Logs only unencrypted"), ("c", "Amazon EBS"), ("d", "Paper mail"), ("e", "On-premises tape only")], ["a", "c"],
     "S3 and EBS support encryption at rest; many services integrate with KMS.",
     [("AWS KMS", "https://docs.aws.amazon.com/kms/latest/developerguide/overview.html")]),
    ("security-compliance", "multiple-choice",
     "AWS Network Firewall is a:",
     [("a", "Managed network firewall for VPCs"), ("b", "S3 storage class"), ("c", "Database engine"), ("d", "Email service")], ["a"],
     "Network Firewall provides stateful inspection for VPC traffic.",
     [("AWS Network Firewall", "https://docs.aws.amazon.com/network-firewall/latest/developerguide/what-is-aws-network-firewall.html")]),
    ("security-compliance", "multiple-choice",
     "Amazon GuardDuty uses primarily:",
     [("a", "Threat detection based on logs and activity"), ("b", "Physical access cards"), ("c", "Domain registration"), ("d", "S3 static hosting")], ["a"],
     "GuardDuty analyzes CloudTrail, VPC Flow Logs, and DNS logs for threats.",
     [("GuardDuty", "https://docs.aws.amazon.com/guardduty/latest/ug/what-is-guardduty.html")]),
    # --- Domain 3: Cloud Technology and Services (34%) ---
    ("technology-services", "multiple-choice",
     "Amazon Elastic File System (EFS) provides:",
     [("a", "Scalable NFS file storage for EC2"), ("b", "Object storage"), ("c", "DNS routing"), ("d", "Relational OLTP only")], ["a"],
     "EFS is managed NFS for Linux workloads across AZs.",
     [("Amazon EFS", "https://docs.aws.amazon.com/efs/latest/ug/whatisefs.html")]),
    ("technology-services", "multiple-choice",
     "AWS Snowball is used to:",
     [("a", "Transfer large amounts of data into and out of AWS"), ("b", "Run Lambda functions"), ("c", "Manage IAM users"), ("d", "Host WordPress only")], ["a"],
     "Snowball devices provide petabyte-scale offline data migration.",
     [("AWS Snowball", "https://docs.aws.amazon.com/snowball/latest/developer-guide/whatissnow.html")]),
    ("technology-services", "multiple-choice",
     "Amazon Redshift is a:",
     [("a", "Data warehouse service"), ("b", "Mobile push service"), ("c", "VPN client"), ("d", "Certificate authority")], ["a"],
     "Redshift is a managed analytics warehouse for SQL queries at scale.",
     [("Amazon Redshift", "https://docs.aws.amazon.com/redshift/latest/mgmt/welcome.html")]),
    ("technology-services", "multiple-choice",
     "AWS Glue is primarily a:",
     [("a", "Serverless data integration and ETL service"), ("b", "CDN"), ("c", "Firewall appliance"), ("d", "Email archive")], ["a"],
     "Glue discovers, prepares, and integrates data for analytics.",
     [("AWS Glue", "https://docs.aws.amazon.com/glue/latest/dg/what-is-glue.html")]),
    ("technology-services", "multiple-choice",
     "Amazon Kinesis is used for:",
     [("a", "Real-time streaming data ingestion and processing"), ("b", "Static website hosting only"), ("c", "IAM federation"), ("d", "Reserved Instance purchases")], ["a"],
     "Kinesis collects, processes, and analyzes streaming data.",
     [("Amazon Kinesis", "https://docs.aws.amazon.com/streams/latest/dev/introduction.html")]),
    ("technology-services", "multiple-choice",
     "AWS Step Functions orchestrates:",
     [("a", "Distributed workflows across AWS services"), ("b", "S3 bucket naming"), ("c", "Physical shipping"), ("d", "Domain transfers")], ["a"],
     "Step Functions coordinates Lambda, ECS, and other services in visual workflows.",
     [("AWS Step Functions", "https://docs.aws.amazon.com/step-functions/latest/dg/welcome.html")]),
    ("technology-services", "multiple-choice",
     "Amazon ElastiCache is used for:",
     [("a", "In-memory caching (Redis/Memcached)"), ("b", "Long-term archival"), ("c", "DNS failover"), ("d", "Compliance PDFs")], ["a"],
     "ElastiCache improves application performance with microsecond latency caching.",
     [("Amazon ElastiCache", "https://docs.aws.amazon.com/AmazonElastiCache/latest/red-ug/WhatIs.html")]),
    ("technology-services", "multiple-choice",
     "AWS App Runner deploys:",
     [("a", "Containerized web applications at scale"), ("b", "On-premises routers"), ("c", "IAM policies"), ("d", "Snowmobile trucks")], ["a"],
     "App Runner builds and runs container apps from source or image with minimal ops.",
     [("AWS App Runner", "https://docs.aws.amazon.com/apprunner/latest/dg/what-is-apprunner.html")]),
    ("technology-services", "multiple-choice",
     "Amazon Lightsail is best for:",
     [("a", "Simple applications, websites, and dev environments at a fixed price"), ("b", "Exabyte-scale data lakes only"), ("c", "Mainframe migration only"), ("d", "IAM organization SCPs")], ["a"],
     "Lightsail bundles compute, storage, and networking for easy projects.",
     [("Amazon Lightsail", "https://docs.aws.amazon.com/lightsail/latest/userguide/what-is-amazon-lightsail.html")]),
    ("technology-services", "multiple-choice",
     "AWS Systems Manager helps you:",
     [("a", "Manage and operate EC2 and hybrid nodes at scale"), ("b", "Replace Route 53"), ("c", "Buy reserved capacity only"), ("d", "Register trademarks")], ["a"],
     "Systems Manager provides patch, run command, parameter store, and inventory features.",
     [("AWS Systems Manager", "https://docs.aws.amazon.com/systems-manager/latest/userguide/what-is-systems-manager.html")]),
    ("technology-services", "multiple-choice",
     "Amazon EMR is used for:",
     [("a", "Big data processing with Apache Spark and Hadoop"), ("b", "Email delivery"), ("c", "SSL certificates"), ("d", "VPC peering only")], ["a"],
     "EMR runs big data frameworks on managed clusters.",
     [("Amazon EMR", "https://docs.aws.amazon.com/emr/latest/ManagementGuide/emr-what-is-emr.html")]),
    ("technology-services", "multiple-choice",
     "AWS Fargate allows you to run containers:",
     [("a", "Without managing servers"), ("b", "Only on-premises"), ("c", "Without networking"), ("d", "Only on Windows 95")], ["a"],
     "Fargate is serverless compute for ECS and EKS workloads.",
     [("AWS Fargate", "https://docs.aws.amazon.com/AmazonECS/latest/developerguide/AWS_Fargate.html")]),
    ("technology-services", "multiple-choice",
     "Amazon WorkSpaces provides:",
     [("a", "Managed desktop virtualization (DaaS)"), ("b", "Object storage"), ("c", "IoT device firmware"), ("d", "Snowball ordering")], ["a"],
     "WorkSpaces delivers cloud-based Windows or Linux desktops.",
     [("Amazon WorkSpaces", "https://docs.aws.amazon.com/workspaces/latest/adminguide/amazon-workspaces.html")]),
    ("technology-services", "multiple-choice",
     "AWS Database Migration Service (DMS) helps:",
     [("a", "Migrate databases to AWS with minimal downtime"), ("b", "Replace CloudFront"), ("c", "Scan malware on laptops"), ("d", "Manage payroll")], ["a"],
     "DMS supports homogeneous and heterogeneous database migrations.",
     [("AWS DMS", "https://docs.aws.amazon.com/dms/latest/userguide/Welcome.html")]),
    ("technology-services", "multiple-choice",
     "Amazon MQ is a managed service for:",
     [("a", "Apache ActiveMQ and RabbitMQ brokers"), ("b", "S3 lifecycle"), ("c", "EC2 reservations"), ("d", "IAM MFA")], ["a"],
     "Amazon MQ hosts message brokers for apps moving from on-premises messaging.",
     [("Amazon MQ", "https://docs.aws.amazon.com/amazon-mq/latest/developer-guide/welcome.html")]),
    ("technology-services", "multiple-choice",
     "AWS Amplify helps developers:",
     [("a", "Build and deploy full-stack web and mobile apps"), ("b", "Operate physical data centers"), ("c", "Replace AWS Organizations"), ("d", "Audit PCI only")], ["a"],
     "Amplify provides frontend hosting, APIs, auth, and CI/CD for apps.",
     [("AWS Amplify", "https://docs.aws.amazon.com/amplify/latest/userguide/welcome.html")]),
    ("technology-services", "multiple-choice",
     "Amazon SageMaker is used for:",
     [("a", "Building, training, and deploying machine learning models"), ("b", "DNS routing"), ("c", "S3 replication only"), ("d", "Snowball repair")], ["a"],
     "SageMaker is a broad ML platform for the full model lifecycle.",
     [("Amazon SageMaker", "https://docs.aws.amazon.com/sagemaker/latest/dg/whatis.html")]),
    ("technology-services", "multiple-choice",
     "AWS Transit Gateway connects:",
     [("a", "VPCs and on-premises networks through a central hub"), ("b", "Only two S3 buckets"), ("c", "IAM users to payroll"), ("d", "Edge locations to laptops only")], ["a"],
     "Transit Gateway simplifies network architecture at scale.",
     [("AWS Transit Gateway", "https://docs.aws.amazon.com/vpc/latest/tgw/what-is-transit-gateway.html")]),
    ("technology-services", "multiple-choice",
     "Amazon DocumentDB (with MongoDB compatibility) is a:",
     [("a", "Managed document database"), ("b", "CDN"), ("c", "Firewall"), ("d", "Data transfer report")], ["a"],
     "DocumentDB stores JSON-like documents with MongoDB API compatibility.",
     [("Amazon DocumentDB", "https://docs.aws.amazon.com/documentdb/latest/developerguide/what-is.html")]),
    ("technology-services", "multiple-response",
     "Which are AWS storage services? (Select TWO.)",
     [("a", "Amazon S3"), ("b", "Amazon EC2 Instance Connect only"), ("c", "Amazon EBS"), ("d", "AWS IAM"), ("e", "Amazon CloudWatch alarms")], ["a", "c"],
     "S3 is object storage; EBS is block storage for EC2.",
     [("AWS Storage", "https://aws.amazon.com/products/storage/")]),
    ("technology-services", "multiple-choice",
     "AWS Direct Connect provides:",
     [("a", "Dedicated private connectivity from on-premises to AWS"), ("b", "Free public internet for all"), ("c", "S3 object encryption keys"), ("d", "Lambda runtime only")], ["a"],
     "Direct Connect establishes private network links to AWS.",
     [("AWS Direct Connect", "https://docs.aws.amazon.com/directconnect/latest/UserGuide/Welcome.html")]),
    ("technology-services", "multiple-choice",
     "Amazon CloudFront integrates with which origin at a high level?",
     [("a", "S3, ALB, EC2, and custom origins"), ("b", "Only paper archives"), ("c", "IAM policies"), ("d", "Cost Explorer")], ["a"],
     "CloudFront caches content from many AWS and custom HTTP origins.",
     [("CloudFront", "https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/Introduction.html")]),
    ("technology-services", "multiple-choice",
     "AWS Batch runs:",
     [("a", "Batch computing jobs at any scale"), ("b", "Real-time chat only"), ("c", "Domain WHOIS"), ("d", "MFA devices")], ["a"],
     "Batch dynamically provisions compute for batch workloads.",
     [("AWS Batch", "https://docs.aws.amazon.com/batch/latest/userguide/what-is-batch.html")]),
    ("technology-services", "multiple-choice",
     "Amazon OpenSearch Service is used for:",
     [("a", "Search, log analytics, and visualization"), ("b", "GPU training only"), ("c", "Snowball ordering"), ("d", "IAM SSO")], ["a"],
     "OpenSearch Service runs OpenSearch/Elasticsearch for search and observability.",
     [("Amazon OpenSearch", "https://docs.aws.amazon.com/opensearch-service/latest/developerguide/what-is.html")]),
    ("technology-services", "multiple-choice",
     "AWS IoT Core enables:",
     [("a", "Connected devices to interact with cloud applications"), ("b", "Only email hosting"), ("c", "Reserved Instance sharing"), ("d", "Artifact downloads")], ["a"],
     "IoT Core is a managed cloud service for billions of devices.",
     [("AWS IoT Core", "https://docs.aws.amazon.com/iot/latest/developerguide/what-is-aws-iot.html")]),
    ("technology-services", "multiple-choice",
     "Amazon FSx provides:",
     [("a", "Managed third-party file systems (Windows, Lustre, NetApp, OpenZFS)"), ("b", "DNS only"), ("c", "IAM keys"), ("d", "Support cases")], ["a"],
     "FSx offers fully managed Windows File Server, Lustre, ONTAP, and more.",
     [("Amazon FSx", "https://docs.aws.amazon.com/fsx/latest/WindowsGuide/what-is.html")]),
    ("technology-services", "multiple-choice",
     "AWS CodeDeploy automates:",
     [("a", "Application deployments to EC2, Lambda, and on-premises"), ("b", "S3 bucket creation only"), ("c", "Root password resets"), ("d", "Snowmobile driving")], ["a"],
     "CodeDeploy rolls out application revisions with minimal downtime.",
     [("AWS CodeDeploy", "https://docs.aws.amazon.com/codedeploy/latest/userguide/welcome.html")]),
    ("technology-services", "multiple-choice",
     "Amazon Rekognition provides:",
     [("a", "Image and video analysis using machine learning"), ("b", "Block storage"), ("c", "VPC peering"), ("d", "Billing consolidation")], ["a"],
     "Rekognition detects objects, faces, text, and inappropriate content in media.",
     [("Amazon Rekognition", "https://docs.aws.amazon.com/rekognition/latest/dg/what-is.html")]),
    ("technology-services", "multiple-choice",
     "AWS Site-to-Site VPN connects:",
     [("a", "Your data center to a VPC over an encrypted tunnel"), ("b", "Two S3 buckets only"), ("c", "Users to Twitter"), ("d", "Artifact to Macie")], ["a"],
     "Site-to-Site VPN creates IPsec tunnels between your network and AWS.",
     [("AWS Site-to-Site VPN", "https://docs.aws.amazon.com/vpn/latest/s2svpn/VPC_VPN.html")]),
    ("technology-services", "multiple-choice",
     "Amazon Comprehend is a:",
     [("a", "Natural language processing (NLP) service"), ("b", "Hardware load balancer"), ("c", "S3 storage tier"), ("d", "Support plan")], ["a"],
     "Comprehend finds insights and relationships in text using ML.",
     [("Amazon Comprehend", "https://docs.aws.amazon.com/comprehend/latest/dg/what-is.html")]),
    # --- Domain 4: Billing, Pricing, and Support (12%) ---
    ("billing-pricing-support", "multiple-choice",
     "The AWS Pricing Calculator helps you:",
     [("a", "Estimate monthly AWS costs before deployment"), ("b", "Patch Windows servers"), ("c", "Create IAM groups"), ("d", "Enable GuardDuty")], ["a"],
     "Build estimates for services and configurations at calculator.aws.",
     [("AWS Pricing Calculator", "https://calculator.aws/")]),
    ("billing-pricing-support", "multiple-choice",
     "Which pricing model lets you use spare EC2 capacity at up to 90% discount with possible interruption?",
     [("a", "Spot Instances"), ("b", "Dedicated Hosts only"), ("c", "On-Demand with no interruption"), ("d", "Enterprise support fee")], ["a"],
     "Spot Instances use unused capacity at steep discounts.",
     [("Spot Instances", "https://aws.amazon.com/ec2/spot/")]),
    ("billing-pricing-support", "multiple-choice",
     "AWS Developer Support plan is differentiated from Basic by:",
     [("a", "Business hours email access to Cloud Support for technical issues"), ("b", "24/7 phone for all accounts"), ("c", "Dedicated TAM"), ("d", "Unlimited free usage")], ["a"],
     "Developer adds technical support during business hours via email.",
     [("Support plans", "https://aws.amazon.com/premiumsupport/")]),
    ("billing-pricing-support", "multiple-choice",
     "Billing alerts based on actual or forecasted spend can be configured in:",
     [("a", "AWS Budgets"), ("b", "Amazon S3"), ("c", "VPC Flow Logs"), ("d", "Amazon EKS")], ["a"],
     "Budgets sends alerts when cost or usage exceeds thresholds you define.",
     [("AWS Budgets", "https://docs.aws.amazon.com/cost-management/latest/userguide/budgets-managing-costs.html")]),
    ("billing-pricing-support", "multiple-choice",
     "Reserved Instance benefits in Organizations consolidated billing:",
     [("a", "Can apply across accounts in the same organization"), ("b", "Never apply across accounts"), ("c", "Only for S3"), ("d", "Only in GovCloud")], ["a"],
     "RI and Savings Plan discounts can share across linked accounts.",
     [("Consolidated billing", "https://docs.aws.amazon.com/awsaccountbilling/latest/aboutv2/consolidated-billing.html")]),
    ("billing-pricing-support", "multiple-choice",
     "AWS Enterprise Support includes:",
     [("a", "Concierge support team and a Technical Account Manager (TAM) option"), ("b", "No technical support"), ("c", "Only documentation"), ("d", "Free Snowmobile")], ["a"],
     "Enterprise provides highest level of proactive and reactive support.",
     [("Enterprise Support", "https://aws.amazon.com/premiumsupport/enterprise/")]),
    ("billing-pricing-support", "multiple-choice",
     "Which tool gives free recommendations to reduce cost and improve security?",
     [("a", "AWS Trusted Advisor"), ("b", "AWS Artifact only"), ("c", "Amazon Polly"), ("d", "AWS Snowball")], ["a"],
     "Trusted Advisor checks cost optimization, performance, security, and fault tolerance.",
     [("Trusted Advisor", "https://docs.aws.amazon.com/awssupport/latest/user/trusted-advisor.html")]),
    ("billing-pricing-support", "multiple-choice",
     "Data transfer IN to AWS from the internet is generally:",
     [("a", "Free for many services"), ("b", "More expensive than transfer out"), ("c", "Charged per IAM user"), ("d", "Not measurable")], ["a"],
     "Inbound data transfer is often free; outbound charges commonly apply (verify per service).",
     [("Data transfer pricing", "https://aws.amazon.com/ec2/pricing/on-demand/#Data_Transfer")]),
    ("billing-pricing-support", "multiple-response",
     "Which are AWS cost management tools? (Select TWO.)",
     [("a", "AWS Cost Explorer"), ("b", "Amazon GuardDuty"), ("c", "AWS Budgets"), ("d", "Amazon Cognito"), ("e", "AWS WAF")], ["a", "c"],
     "Cost Explorer and Budgets help analyze and control spending.",
     [("AWS Billing and Cost Management", "https://docs.aws.amazon.com/awsaccountbilling/latest/aboutv2/billing-what-is.html")]),
    ("billing-pricing-support", "multiple-choice",
     "On-Demand Instances are ideal when:",
     [("a", "You need short-term, flexible compute without upfront payment"), ("b", "You require 3-year commitment"), ("c", "You cannot tolerate stopping"), ("d", "You only use Spot")], ["a"],
     "On-Demand has no commitment; pay per second/hour depending on service.",
     [("On-Demand pricing", "https://aws.amazon.com/ec2/pricing/on-demand/")]),
    ("billing-pricing-support", "multiple-choice",
     "AWS Marketplace allows customers to:",
     [("a", "Find, buy, and deploy third-party software on AWS"), ("b", "Replace AWS Support"), ("c", "Avoid all charges"), ("d", "Manage physical cables")], ["a"],
     "Marketplace offers SaaS, AMIs, and data products from independent vendors.",
     [("AWS Marketplace", "https://aws.amazon.com/marketplace")]),
]
