"""Per-exam service and concept facts used to synthesize practice MCQs (not real exam items)."""
from __future__ import annotations

# Each fact: (stem_suffix, correct, [wrong_a, wrong_b, wrong_c], explanation, doc_title, doc_url)
Fact = tuple[str, str, list[str], str, str, str]

# fmt: off
BANKS: dict[str, dict[str, list[Fact]]] = {
    "ai-practitioner": {
        "ai-ml-fundamentals": [
            ("train and deploy custom ML models with managed infrastructure", "Amazon SageMaker",
             ["Amazon Rekognition", "Amazon Polly", "AWS Batch"], "SageMaker provides end-to-end ML building, training, and deployment.",
             "Amazon SageMaker", "https://docs.aws.amazon.com/sagemaker/latest/dg/whatis.html"),
            ("label raw data for supervised learning at scale", "Amazon SageMaker Ground Truth",
             ["Amazon Macie", "AWS Artifact", "Amazon Connect"], "Ground Truth helps create labeled datasets using human and automated labeling.",
             "SageMaker Ground Truth", "https://docs.aws.amazon.com/sagemaker/latest/dg/sms.html"),
            ("run batch inference on large datasets without managing servers", "Amazon SageMaker Batch Transform",
             ["Amazon EC2 Auto Scaling only", "AWS Snowball", "Amazon Route 53"], "Batch Transform runs predictions on large datasets asynchronously.",
             "Batch Transform", "https://docs.aws.amazon.com/sagemaker/latest/dg/batch-transform.html"),
            ("store and version ML model artifacts", "Amazon SageMaker Model Registry",
             ["Amazon S3 Glacier only", "AWS Secrets Manager", "Amazon MQ"], "Model Registry catalogs models for approval and deployment workflows.",
             "Model Registry", "https://docs.aws.amazon.com/sagemaker/latest/dg/model-registry.html"),
            ("perform time-series forecasting with AutoML capabilities", "Amazon SageMaker Canvas or Autopilot",
             ["Amazon Kinesis Video Streams", "AWS WAF", "Amazon SES"], "SageMaker Autopilot and Canvas support low-code ML including forecasting use cases.",
             "SageMaker Autopilot", "https://docs.aws.amazon.com/sagemaker/latest/dg/autopilot-automate-model-development.html"),
            ("classify images with a pre-trained API without building models", "Amazon Rekognition",
             ["AWS Glue", "Amazon Redshift", "AWS CloudTrail"], "Rekognition provides pre-built computer vision APIs.",
             "Amazon Rekognition", "https://docs.aws.amazon.com/rekognition/latest/dg/what-is.html"),
            ("convert text to lifelike speech", "Amazon Polly",
             ["Amazon Textract", "Amazon Comprehend", "AWS Lambda only"], "Polly is a text-to-speech service.",
             "Amazon Polly", "https://docs.aws.amazon.com/polly/latest/dg/what-is.html"),
            ("extract text and data from scanned documents", "Amazon Textract",
             ["Amazon Polly", "Amazon MQ", "AWS Direct Connect"], "Textract uses ML to read forms and tables from documents.",
             "Amazon Textract", "https://docs.aws.amazon.com/textract/latest/dg/what-is.html"),
            ("discover insights and relationships in unstructured text", "Amazon Comprehend",
             ["Amazon EBS", "AWS Shield", "Amazon VPC"], "Comprehend is a natural language processing (NLP) service.",
             "Amazon Comprehend", "https://docs.aws.amazon.com/comprehend/latest/dg/what-is.html"),
            ("translate text between languages at scale", "Amazon Translate",
             ["Amazon Route 53", "AWS Config", "Amazon Inspector"], "Translate provides neural machine translation.",
             "Amazon Translate", "https://docs.aws.amazon.com/translate/latest/dg/what-is.html"),
            ("search for similar vectors in embedding datasets", "Amazon OpenSearch Service or Aurora pgvector",
             ["Amazon S3 Glacier Deep Archive only", "AWS Budgets", "Amazon WorkSpaces"], "Vector search supports similarity queries for embeddings in search engines or databases.",
             "OpenSearch k-NN", "https://docs.aws.amazon.com/opensearch-service/latest/developerguide/knn.html"),
            ("orchestrate ML pipelines with repeatable steps", "Amazon SageMaker Pipelines",
             ["Amazon SNS", "AWS Artifact", "Amazon Lightsail"], "SageMaker Pipelines automates end-to-end ML workflows.",
             "SageMaker Pipelines", "https://docs.aws.amazon.com/sagemaker/latest/dg/pipelines.html"),
        ],
        "generative-ai-fundamentals": [
            ("access foundation models from multiple providers through one API", "Amazon Bedrock",
             ["Amazon EC2 only", "AWS Snowcone", "Amazon RDS"], "Bedrock offers FMs from Amazon and partners via a unified API.",
             "Amazon Bedrock", "https://docs.aws.amazon.com/bedrock/latest/userguide/what-is-bedrock.html"),
            ("invoke models for text generation with on-demand throughput", "Amazon Bedrock",
             ["Amazon S3", "AWS CloudFormation", "Amazon EFS"], "Bedrock supports on-demand and provisioned throughput for inference.",
             "Bedrock inference", "https://docs.aws.amazon.com/bedrock/latest/userguide/inference.html"),
            ("customize a foundation model with labeled examples for a specific task", "Amazon Bedrock model customization (fine-tuning)",
             ["AWS KMS only", "Amazon CloudWatch Logs only", "VPC Flow Logs"], "Fine-tuning adapts FMs using your domain-specific data.",
             "Model customization", "https://docs.aws.amazon.com/bedrock/latest/userguide/custom-models.html"),
            ("compare latency and quality across foundation models in a playground", "Amazon Bedrock console playgrounds",
             ["AWS Cost Explorer only", "Amazon Inspector", "AWS Artifact"], "Playgrounds let you experiment with prompts and models.",
             "Bedrock playgrounds", "https://docs.aws.amazon.com/bedrock/latest/userguide/playgrounds.html"),
            ("generate images from text prompts using AWS generative AI", "Amazon Titan Image Generator or Stability AI models in Bedrock",
             ["Amazon Glacier", "AWS DataSync only", "Amazon MQ"], "Bedrock supports image generation models for creative workloads.",
             "Bedrock image models", "https://docs.aws.amazon.com/bedrock/latest/userguide/model-ids.html"),
            ("understand tokens as billing units for generative models", "Token-based pricing on Amazon Bedrock",
             ["EBS volume IOPS", "Data transfer in only", "IAM policy size"], "Generative models often bill per input/output tokens.",
             "Bedrock pricing", "https://aws.amazon.com/bedrock/pricing/"),
            ("reduce hallucinations by grounding responses in private data", "Retrieval Augmented Generation (RAG)",
             ["Spot Instances", "S3 Transfer Acceleration only", "Reserved Instances"], "RAG retrieves relevant documents before the model generates an answer.",
             "RAG on Bedrock", "https://docs.aws.amazon.com/bedrock/latest/userguide/knowledge-base.html"),
            ("store prompt templates and versions for teams", "Amazon Bedrock Prompt Management or similar versioning patterns",
             ["Amazon S3 lifecycle only", "Route 53", "AWS Snowmobile"], "Managing prompts as code/templates improves consistency and governance.",
             "Prompt engineering", "https://docs.aws.amazon.com/bedrock/latest/userguide/prompt-management.html"),
            ("evaluate model outputs for quality before production", "Model evaluation in Amazon Bedrock or SageMaker",
             ["AWS Budgets", "Amazon Cognito only", "VPC peering"], "Systematic evaluation compares models and prompts against benchmarks.",
             "Bedrock evaluation", "https://docs.aws.amazon.com/bedrock/latest/userguide/model-evaluation.html"),
            ("use embeddings to represent text for semantic search", "Amazon Titan Embeddings or Cohere Embed on Bedrock",
             ["Amazon EBS snapshots", "AWS Shield Standard only", "Amazon WorkMail"], "Embeddings convert text to vectors for similarity search.",
             "Embeddings", "https://docs.aws.amazon.com/bedrock/latest/userguide/embeddings.html"),
        ],
        "foundation-model-applications": [
            ("build a conversational assistant that calls APIs and queries data", "Amazon Bedrock Agents",
             ["Amazon S3 Intelligent-Tiering only", "AWS Snowball Edge", "Amazon RDS Proxy only"], "Agents orchestrate FM reasoning with tools and knowledge bases.",
             "Bedrock Agents", "https://docs.aws.amazon.com/bedrock/latest/userguide/agents.html"),
            ("connect private documents to a foundation model for Q&A", "Knowledge Bases for Amazon Bedrock",
             ["Amazon Glacier", "AWS Artifact", "Amazon Lightsail"], "Knowledge bases ingest, chunk, embed, and retrieve documents for RAG.",
             "Knowledge Bases", "https://docs.aws.amazon.com/bedrock/latest/userguide/knowledge-base.html"),
            ("chunk documents and store vectors for retrieval", "Amazon OpenSearch Serverless or Amazon Aurora vector store with Bedrock",
             ["Amazon SNS FIFO only", "AWS WAF", "Amazon Macie only for blocking"], "Vector stores hold embeddings for semantic retrieval in RAG pipelines.",
             "Knowledge base vector stores", "https://docs.aws.amazon.com/bedrock/latest/userguide/knowledge-base-setup.html"),
            ("expose a generative AI feature behind a REST API to web clients", "Amazon API Gateway with AWS Lambda and Bedrock",
             ["Amazon EBS", "AWS Direct Connect only", "Amazon Inspector"], "API Gateway + Lambda is a common serverless pattern for GenAI apps.",
             "API Gateway", "https://docs.aws.amazon.com/apigateway/latest/developerguide/welcome.html"),
            ("cache frequent model responses to reduce cost and latency", "Amazon ElastiCache or API-level caching",
             ["AWS Snowmobile", "Amazon WorkSpaces", "AWS Artifact"], "Caching repeated prompts lowers inference spend and improves UX.",
             "Amazon ElastiCache", "https://docs.aws.amazon.com/AmazonElastiCache/latest/red-ug/WhatIs.html"),
            ("run inference in a VPC without public internet for data residency", "Amazon Bedrock VPC endpoints",
             ["Public S3 buckets", "Root access keys in code", "Unencrypted EBS only"], "VPC endpoints keep Bedrock traffic on the AWS network.",
             "Bedrock VPC", "https://docs.aws.amazon.com/bedrock/latest/userguide/vpc-interface-endpoints.html"),
            ("stream tokens to clients for responsive chat UIs", "Amazon Bedrock Converse API with streaming",
             ["Batch Transform only", "S3 Glacier", "AWS Organizations SCPs only"], "Streaming returns partial responses as the model generates text.",
             "Converse API", "https://docs.aws.amazon.com/bedrock/latest/userguide/conversation-inference.html"),
            ("moderate harmful content in model inputs and outputs", "Amazon Bedrock Guardrails",
             ["Amazon Route 53 health checks only", "AWS CUR", "Snowball"], "Guardrails filter topics, PII, and harmful content.",
             "Guardrails", "https://docs.aws.amazon.com/bedrock/latest/userguide/guardrails.html"),
            ("log prompts and completions for audit", "Amazon CloudWatch Logs and model invocation logging",
             ["Amazon Polly only", "AWS Budgets", "Amazon MQ"], "Invocation logging supports compliance and troubleshooting.",
             "Model invocation logging", "https://docs.aws.amazon.com/bedrock/latest/userguide/model-invocation-logging.html"),
            ("deploy a small custom model at the edge", "AWS IoT Greengrass with optimized models or edge devices",
             ["Amazon Redshift", "AWS Glue DataBrew only", "Amazon Connect"], "Edge inference places models closer to devices when cloud latency is too high.",
             "Edge ML", "https://docs.aws.amazon.com/greengrass/v2/developerguide/what-is-greengrass.html"),
        ],
        "responsible-ai": [
            ("detect bias and explain model predictions", "Amazon SageMaker Clarify",
             ["Amazon S3", "AWS WAF", "Amazon API Gateway"], "Clarify provides fairness and explainability tools for ML.",
             "SageMaker Clarify", "https://docs.aws.amazon.com/sagemaker/latest/dg/clarify-fairness-and-explainability.html"),
            ("document model cards and human review for high-risk AI", "Responsible AI governance processes on AWS",
             ["Disabling CloudTrail", "Sharing root keys", "Public AMIs by default"], "Governance includes documentation, human oversight, and risk assessment.",
             "Responsible AI", "https://aws.amazon.com/machine-learning/responsible-ai/"),
            ("ensure training data represents diverse populations", "Inclusive dataset design and Clarify bias metrics",
             ["Using only synthetic test users", "Ignoring class imbalance", "Removing all labels"], "Representative data reduces unfair outcomes across groups.",
             "Fairness in ML", "https://docs.aws.amazon.com/sagemaker/latest/dg/clarify-data-bias-metrics.html"),
            ("inform users they interact with AI-generated content", "Transparency and disclosure best practices",
             ["Hiding model limitations", "Publishing root credentials", "Disabling encryption"], "Transparency builds trust and meets emerging AI regulations.",
             "Responsible AI practices", "https://aws.amazon.com/machine-learning/responsible-ai/"),
            ("minimize collection of personal data in fine-tuning datasets", "Data minimization and anonymization",
             ["Storing all PII in prompts", "Public datasets with secrets", "No access controls"], "Collect only necessary data and remove identifiers where possible.",
             "Data protection on AWS", "https://docs.aws.amazon.com/whitepapers/latest/introduction-aws-security/data-protection.html"),
            ("establish human-in-the-loop for consequential decisions", "Amazon A2I or review workflows in SageMaker",
             ["Fully automated approvals with no audit", "Deleting all logs", "Single-AZ only"], "Human review reduces risk for high-impact predictions.",
             "Amazon A2I", "https://docs.aws.amazon.com/sagemaker/latest/dg/a2i-use-augmented-ai-a2i-human-review-loops.html"),
            ("test models for robustness to prompt injection", "Red teaming and guardrails for GenAI",
             ["Disabling authentication", "Using production data in dev without controls", "Ignoring OWASP LLM risks"], "Adversarial prompt testing improves GenAI application security.",
             "GenAI security", "https://docs.aws.amazon.com/bedrock/latest/userguide/guardrails.html"),
            ("track model lineage from dataset to deployment", "Amazon SageMaker Lineage or MLflow on SageMaker",
             ["Unversioned S3 overwrites only", "No tags", "Shared IAM users"], "Lineage supports reproducibility and audit.",
             "SageMaker Lineage", "https://docs.aws.amazon.com/sagemaker/latest/dg/lineage-tracking.html"),
        ],
        "ai-security-governance": [
            ("encrypt model artifacts and training data at rest", "AWS KMS with Amazon S3 and SageMaker",
             ["HTTP only", "Public buckets", "Plaintext secrets in code"], "KMS manages keys for encryption across AI data stores.",
             "AWS KMS", "https://docs.aws.amazon.com/kms/latest/developerguide/overview.html"),
            ("control which IAM principals can invoke Bedrock models", "IAM policies for bedrock:InvokeModel",
             ["Anonymous access", "Root user daily use", "Wildcard * on all actions for everyone"], "Least-privilege IAM restricts model access.",
             "Bedrock IAM", "https://docs.aws.amazon.com/bedrock/latest/userguide/security-iam.html"),
            ("discover sensitive training data in S3 buckets", "Amazon Macie",
             ["Amazon Polly", "AWS Snowball only", "Route 53"], "Macie finds PII and sensitive data in object storage.",
             "Amazon Macie", "https://docs.aws.amazon.com/macie/latest/user/what-is-macie.html"),
            ("audit API calls to AI services", "AWS CloudTrail",
             ["Amazon Rekognition only for DNS", "S3 lifecycle", "EBS encryption by default only"], "CloudTrail logs management and data events for governance.",
             "CloudTrail", "https://docs.aws.amazon.com/awscloudtrail/latest/userguide/cloudtrail-user-guide.html"),
            ("isolate training jobs in a private network", "Amazon SageMaker in VPC mode",
             ["Internet-facing databases with no auth", "0.0.0.0/0 on all ports", "Public subnets only for data"], "VPC config keeps training traffic private.",
             "SageMaker VPC", "https://docs.aws.amazon.com/sagemaker/latest/dg/interface-vpc-endpoint.html"),
            ("rotate API keys and secrets for third-party models", "AWS Secrets Manager",
             ["Hard-coded keys in Git", "Emailing passwords", "S3 public ACLs"], "Secrets Manager automates secret rotation.",
             "Secrets Manager", "https://docs.aws.amazon.com/secretsmanager/latest/userguide/intro.html"),
            ("apply organizational policies across AI accounts", "AWS Organizations SCPs",
             ["Single shared root password", "No logging", "Disable MFA"], "SCPs set guardrails for services including Bedrock and SageMaker.",
             "Organizations SCPs", "https://docs.aws.amazon.com/organizations/latest/userguide/orgs_manage_policies_scps.html"),
            ("monitor model endpoints for drift", "Amazon SageMaker Model Monitor",
             ["Amazon SES", "AWS Artifact only", "Amazon Lightsail"], "Model Monitor detects data and quality drift in production.",
             "Model Monitor", "https://docs.aws.amazon.com/sagemaker/latest/dg/model-monitor.html"),
        ],
    },
    "solutions-architect-associate": {
        "resilient-architectures": [
            ("distribute incoming application traffic across multiple targets", "Elastic Load Balancing",
             ["Amazon S3", "AWS Glue", "Amazon Macie"], "ELB health-checks targets and routes traffic.",
             "Elastic Load Balancing", "https://docs.aws.amazon.com/elasticloadbalancing/latest/userguide/what-is-load-balancing.html"),
            ("route DNS traffic based on latency, geolocation, or failover", "Amazon Route 53",
             ["Amazon EBS", "AWS Batch", "Amazon Polly"], "Route 53 supports multiple routing policies for resilience.",
             "Route 53", "https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/routing-policy.html"),
            ("replicate a relational database to a standby in another AZ", "Amazon RDS Multi-AZ",
             ["Single-AZ RDS with no backups", "S3 Standard only", "On-premises tape"], "Multi-AZ synchronously replicates for HA within a Region.",
             "RDS Multi-AZ", "https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/Concepts.MultiAZ.html"),
            ("store static assets with high durability and serve globally", "Amazon S3 with Amazon CloudFront",
             ["Amazon EBS only", "Instance store only", "Amazon MQ"], "S3 plus CloudFront delivers durable storage and edge caching.",
             "Amazon S3", "https://docs.aws.amazon.com/AmazonS3/latest/userguide/Welcome.html"),
            ("automatically replace unhealthy EC2 instances in a group", "Amazon EC2 Auto Scaling with ELB",
             ["Manual SSH fixes only", "Single instance", "Disabling health checks"], "Auto Scaling maintains desired capacity using health checks.",
             "Auto Scaling", "https://docs.aws.amazon.com/autoscaling/ec2/userguide/what-is-amazon-ec2-auto-scaling.html"),
            ("cache database read-heavy workloads in memory", "Amazon ElastiCache",
             ["Amazon Glacier", "AWS Snowball", "Amazon WorkDocs"], "ElastiCache (Redis/Memcached) reduces database load.",
             "Amazon ElastiCache", "https://docs.aws.amazon.com/AmazonElastiCache/latest/red-ug/WhatIs.html"),
            ("decouple microservices with asynchronous messaging", "Amazon SQS or Amazon SNS",
             ["Direct tight coupling only", "Shared local disk", "FTP"], "Messaging improves fault isolation between services.",
             "Amazon SQS", "https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/welcome.html"),
            ("backup on-premises workloads to AWS for DR", "AWS Backup or AWS Elastic Disaster Recovery",
             ["Deleting snapshots", "Single AZ only", "No RTO planning"], "AWS Backup centralizes backup policies across services.",
             "AWS Backup", "https://docs.aws.amazon.com/aws-backup/latest/devguide/whatisbackup.html"),
            ("run active-active databases across Regions", "Amazon DynamoDB global tables or Aurora Global Database",
             ["Single laptop SQLite", "Unreplicated EBS", "No backups"], "Global databases support multi-Region resilience.",
             "DynamoDB global tables", "https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/GlobalTables.html"),
            ("protect against DDoS at the edge", "AWS Shield and AWS WAF with CloudFront",
             ["Public SSH on port 22", "Disabled logging", "Root keys in Git"], "Shield and WAF mitigate network and application attacks.",
             "AWS Shield", "https://docs.aws.amazon.com/waf/latest/developerguide/shield-chapter.html"),
        ],
        "high-performing-architectures": [
            ("serve content from edge locations close to users", "Amazon CloudFront",
             ["Amazon RDS", "AWS Config", "Amazon Inspector"], "CloudFront is AWS's global CDN.",
             "CloudFront", "https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/Introduction.html"),
            ("run code without managing servers for spiky traffic", "AWS Lambda",
             ["Physical colocation only", "Single large EC2 with no scaling", "Tape backup"], "Lambda scales automatically with request volume.",
             "AWS Lambda", "https://docs.aws.amazon.com/lambda/latest/dg/welcome.html"),
            ("use a purpose-built NoSQL database with single-digit ms latency at any scale", "Amazon DynamoDB",
             ["Self-hosted FTP", "Amazon EBS", "Amazon WorkSpaces"], "DynamoDB scales horizontally for high-throughput workloads.",
             "DynamoDB", "https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Introduction.html"),
            ("process streaming data in real time", "Amazon Kinesis Data Streams or Managed Service for Apache Flink",
             ["Batch-only cron on one server", "S3 Glacier for hot path", "Email polling"], "Kinesis ingests and processes streaming data.",
             "Kinesis", "https://docs.aws.amazon.com/streams/latest/dev/introduction.html"),
            ("accelerate transfer of large datasets into S3", "AWS DataSync or S3 Transfer Acceleration",
             ["Serial floppy disks", "Uncompressed HTTP only", "Disabling multipart upload"], "DataSync automates secure online data transfer.",
             "AWS DataSync", "https://docs.aws.amazon.com/datasync/latest/userguide/what-is-datasync.html"),
            ("use GP3 or io2 EBS volumes for consistent IOPS", "Amazon EBS volume types",
             ["Instance store for all backups", "S3 for block IO", "Route 53"], "EBS offers SSD volumes tuned for throughput and IOPS.",
             "EBS volume types", "https://docs.aws.amazon.com/ebs/latest/userguide/ebs-volume-types.html"),
            ("place EC2 instances in a cluster placement group for HPC", "EC2 cluster placement groups",
             ["Random regions", "Single thread only", "No networking"], "Cluster placement minimizes latency between instances.",
             "Placement groups", "https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/placement-groups.html"),
            ("analyze petabytes of data in a data warehouse", "Amazon Redshift",
             ["Amazon SNS", "Amazon Cognito", "AWS Artifact"], "Redshift is a managed petabyte-scale warehouse.",
             "Amazon Redshift", "https://docs.aws.amazon.com/redshift/latest/mgmt/welcome.html"),
            ("use ElastiCache to reduce read latency for sessions", "Amazon ElastiCache for Redis",
             ["Amazon Glacier", "AWS Snowcone only", "Amazon Macie"], "Redis provides sub-millisecond in-memory data access.",
             "ElastiCache Redis", "https://docs.aws.amazon.com/AmazonElastiCache/latest/red-ug/WhatIs.html"),
            ("deliver API traffic with throttling and caching", "Amazon API Gateway",
             ["Raw TCP to database", "S3 as API server only", "FTP"], "API Gateway manages REST/HTTP APIs at scale.",
             "API Gateway", "https://docs.aws.amazon.com/apigateway/latest/developerguide/welcome.html"),
        ],
        "secure-architectures": [
            ("enforce MFA and least privilege for human access", "AWS IAM with MFA",
             ["Shared root credentials", "Wildcard admin for all users", "Public S3 ACLs"], "IAM policies and MFA protect account access.",
             "IAM best practices", "https://docs.aws.amazon.com/IAM/latest/UserGuide/best-practices.html"),
            ("encrypt data at rest in S3 with customer-managed keys", "SSE-KMS on Amazon S3",
             ["Unencrypted public buckets", "HTTP only", "Disable versioning"], "SSE-KMS integrates with AWS KMS for key control.",
             "S3 encryption", "https://docs.aws.amazon.com/AmazonS3/latest/userguide/UsingEncryption.html"),
            ("filter HTTP requests for SQL injection and XSS", "AWS WAF",
             ["Security groups only for L7 rules", "NACL for app logic", "S3 lifecycle"], "WAF protects web applications at Layer 7.",
             "AWS WAF", "https://docs.aws.amazon.com/waf/latest/developerguide/waf-chapter.html"),
            ("provide temporary credentials to applications", "IAM roles with STS",
             ["Long-term access keys in code", "Root user for apps", "Passwords in AMIs"], "Roles supply short-lived credentials via STS.",
             "IAM roles", "https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles.html"),
            ("detect malicious activity and unauthorized behavior", "Amazon GuardDuty",
             ["Amazon Polly", "AWS Budgets", "Amazon Lightsail"], "GuardDuty analyzes CloudTrail, VPC Flow Logs, and DNS.",
             "GuardDuty", "https://docs.aws.amazon.com/guardduty/latest/ug/what-is-guardduty.html"),
            ("private connectivity from VPC to AWS services without internet", "VPC interface endpoints (AWS PrivateLink)",
             ["0.0.0.0/0 on database port", "Public subnets for DB only", "Telnet"], "Interface endpoints keep traffic on the AWS network.",
             "VPC endpoints", "https://docs.aws.amazon.com/vpc/latest/privatelink/vpc-endpoints.html"),
            ("centralize security findings across accounts", "AWS Security Hub",
             ["Amazon Rekognition for CVEs", "S3 analytics only", "Route 53"], "Security Hub aggregates compliance and threat findings.",
             "Security Hub", "https://docs.aws.amazon.com/securityhub/latest/userguide/what-is-securityhub.html"),
            ("record all API activity for audit", "AWS CloudTrail",
             ["Deleting logs daily", "No IAM", "Disable encryption"], "CloudTrail logs management events across services.",
             "CloudTrail", "https://docs.aws.amazon.com/awscloudtrail/latest/userguide/cloudtrail-user-guide.html"),
            ("manage SSL/TLS certificates for ALB and CloudFront", "AWS Certificate Manager",
             ["Self-signed only in prod without rotation", "FTP certificates", "SSH keys for HTTPS"], "ACM provisions and renews TLS certificates.",
             "ACM", "https://docs.aws.amazon.com/acm/latest/userguide/acm-overview.html"),
            ("isolate subnets with stateless subnet firewalls", "Network ACLs combined with security groups",
             ["Open SG 0.0.0.0/0 on all ports", "No segmentation", "Public RDS"], "Defense in depth uses NACLs and security groups.",
             "VPC security", "https://docs.aws.amazon.com/vpc/latest/userguide/VPC_Security.html"),
        ],
        "cost-optimized-architectures": [
            ("commit to consistent compute usage for lower hourly rates", "AWS Savings Plans or Reserved Instances",
             ["On-Demand only for steady 24/7", "Ignoring rightsizing", "Over-provisioning always"], "Commitment discounts reduce compute cost for steady workloads.",
             "Savings Plans", "https://docs.aws.amazon.com/savingsplans/latest/userguide/what-is-savings-plans.html"),
            ("use spare EC2 capacity at steep discount for fault-tolerant batch", "Amazon EC2 Spot Instances",
             ["Dedicated Hosts for all stateful DBs without DR", "On-Demand for interruptible only", "Largest instance always"], "Spot offers unused capacity at lower prices.",
             "Spot Instances", "https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/using-spot-instances.html"),
            ("analyze spending trends and forecasts", "AWS Cost Explorer",
             ["Disabling CUR", "No tags", "Ignoring recommendations"], "Cost Explorer visualizes and forecasts AWS spend.",
             "Cost Explorer", "https://docs.aws.amazon.com/cost-management/latest/userguide/ce-what-is.html"),
            ("move infrequently accessed data to cheaper storage class", "Amazon S3 Intelligent-Tiering or Glacier classes",
             ["Standard for all archival", "Deleting objects instead of tiering", "No lifecycle"], "S3 storage classes optimize cost by access pattern.",
             "S3 storage classes", "https://docs.aws.amazon.com/AmazonS3/latest/userguide/storage-class-intro.html"),
            ("stop non-production instances on a schedule", "Instance scheduling with Lambda or Instance Scheduler",
             ["Leave dev running 24/7", "No monitoring", "Maximum size always"], "Scheduling reduces off-hours waste.",
             "Instance Scheduler", "https://docs.aws.amazon.com/solutions/latest/instance-scheduler-on-aws/welcome.html"),
            ("right-size EC2 using utilization metrics", "AWS Compute Optimizer",
             ["Never review metrics", "One size fits all", "Ignore CPU graphs"], "Compute Optimizer recommends instance sizes.",
             "Compute Optimizer", "https://docs.aws.amazon.com/compute-optimizer/latest/ug/what-is-compute-optimizer.html"),
            ("share Reserved Instance benefits across accounts", "AWS Organizations consolidated billing",
             ["Separate unlinked accounts only", "No CUR", "Disable Cost Allocation Tags"], "Consolidated billing shares RI/SP discounts.",
             "Consolidated billing", "https://docs.aws.amazon.com/awsaccountbilling/latest/aboutv2/consolidated-billing.html"),
            ("archive EBS snapshots no longer needed", "Snapshot lifecycle policies",
             ["Infinite snapshots", "No lifecycle", "Public snapshots"], "Lifecycle policies delete stale snapshots to save cost.",
             "EBS snapshots", "https://docs.aws.amazon.com/ebs/latest/userguide/ebs-deleting-snaps.html"),
            ("use Aurora Serverless v2 for variable database load", "Amazon Aurora Serverless v2",
             ["Largest provisioned instance 24/7 for spiky dev", "Self-managed on laptop", "No auto pause/scaling"], "Serverless v2 scales ACUs with demand.",
             "Aurora Serverless", "https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/aurora-serverless.html"),
            ("deliver static websites from S3 without EC2", "Amazon S3 static website hosting with CloudFront",
             ["EC2 fleet for static PNGs only", "EFS for HTML only at highest tier", "VPN for images"], "S3 + CloudFront minimizes compute for static sites.",
             "S3 static hosting", "https://docs.aws.amazon.com/AmazonS3/latest/userguide/WebsiteHosting.html"),
        ],
    },
}
# fmt: on
