#!/usr/bin/env python3
"""Regenerate data/cloud-practitioner.json — run from repo root."""
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
EXAMS_DIR = ROOT / "data" / "exams"
OUT = EXAMS_DIR / "cloud-practitioner.json"
sys.path.insert(0, str(ROOT / "scripts"))

from question_bank.clf_c02_extended import EXTENDED  # noqa: E402

DOMAINS = [
    {
        "id": "cloud-concepts",
        "name": "Domain 1: Cloud Concepts",
        "weight": 24,
        "resources": [
            {
                "title": "AWS Cloud Practitioner Essentials (Skill Builder)",
                "url": "https://aws.amazon.com/training/learn-about/cloud-practitioner/",
            },
            {
                "title": "What is Cloud Computing?",
                "url": "https://aws.amazon.com/what-is-cloud-computing/",
            },
            {
                "title": "AWS Well-Architected Framework",
                "url": "https://docs.aws.amazon.com/wellarchitected/latest/framework/welcome.html",
            },
            {
                "title": "AWS Global Infrastructure",
                "url": "https://aws.amazon.com/about-aws/global-infrastructure/",
            },
        ],
    },
    {
        "id": "security-compliance",
        "name": "Domain 2: Security and Compliance",
        "weight": 30,
        "resources": [
            {
                "title": "AWS Shared Responsibility Model",
                "url": "https://aws.amazon.com/compliance/shared-responsibility-model/",
            },
            {
                "title": "AWS Identity and Access Management (IAM)",
                "url": "https://docs.aws.amazon.com/IAM/latest/UserGuide/introduction.html",
            },
            {
                "title": "AWS Cloud Security",
                "url": "https://aws.amazon.com/security/",
            },
            {
                "title": "AWS Compliance Programs",
                "url": "https://aws.amazon.com/compliance/programs/",
            },
        ],
    },
    {
        "id": "technology-services",
        "name": "Domain 3: Cloud Technology and Services",
        "weight": 34,
        "resources": [
            {
                "title": "AWS Core Services Overview",
                "url": "https://aws.amazon.com/products/",
            },
            {
                "title": "Amazon EC2 User Guide",
                "url": "https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/concepts.html",
            },
            {
                "title": "Amazon S3 User Guide",
                "url": "https://docs.aws.amazon.com/AmazonS3/latest/userguide/Welcome.html",
            },
            {
                "title": "AWS Database Services",
                "url": "https://aws.amazon.com/products/databases/",
            },
        ],
    },
    {
        "id": "billing-pricing-support",
        "name": "Domain 4: Billing, Pricing, and Support",
        "weight": 12,
        "resources": [
            {
                "title": "AWS Pricing",
                "url": "https://aws.amazon.com/pricing/",
            },
            {
                "title": "AWS Billing and Cost Management",
                "url": "https://docs.aws.amazon.com/awsaccountbilling/latest/aboutv2/billing-what-is.html",
            },
            {
                "title": "AWS Support Plans",
                "url": "https://aws.amazon.com/premiumsupport/",
            },
            {
                "title": "AWS Cost Explorer",
                "url": "https://docs.aws.amazon.com/cost-management/latest/userguide/ce-what-is.html",
            },
        ],
    },
]

# (domain, type, text, options as list of (id, text), correct ids, explanation, doc url title pairs)
RAW = [
    ("cloud-concepts", "multiple-choice",
     "Which benefit of cloud computing lets you provision resources in minutes instead of waiting weeks for hardware?",
     [("a", "Elasticity"), ("b", "Agility"), ("c", "Durability"), ("d", "Availability")], ["b"],
     "Agility is the ability to provision and release resources quickly to experiment and respond to change.",
     [("What is Cloud Computing?", "https://aws.amazon.com/what-is-cloud-computing/")]),
    ("cloud-concepts", "multiple-choice",
     "A company wants to pay only for the compute capacity it uses, with no long-term contracts. Which cloud model supports this?",
     [("a", "CapEx model"), ("b", "Pay-as-you-go pricing"), ("c", "Reserved licensing"), ("d", "Dedicated hosting")], ["b"],
     "Pay-as-you-go converts capital expense to variable operational expense.",
     [("AWS Pricing", "https://aws.amazon.com/pricing/")]),
    ("cloud-concepts", "multiple-choice",
     "Which AWS Well-Architected pillar focuses on protecting information and systems?",
     [("a", "Operational Excellence"), ("b", "Security"), ("c", "Performance Efficiency"), ("d", "Cost Optimization")], ["b"],
     "The Security pillar covers confidentiality, integrity, and availability of data and systems.",
     [("Well-Architected Framework", "https://docs.aws.amazon.com/wellarchitected/latest/framework/welcome.html")]),
    ("cloud-concepts", "multiple-choice",
     "What is an Availability Zone?",
     [("a", "A geographic area with multiple isolated locations"), ("b", "One or more discrete data centers with redundant power and networking"),
      ("c", "A content delivery edge location"), ("d", "A virtual private network endpoint")], ["b"],
     "An AZ is one or more data centers in a Region, designed for isolation from failures in other AZs.",
     [("Global Infrastructure", "https://aws.amazon.com/about-aws/global-infrastructure/")]),
    ("cloud-concepts", "multiple-choice",
     "Which deployment model gives a company exclusive use of cloud infrastructure on-premises while using AWS-managed services patterns?",
     [("a", "Public cloud"), ("b", "Hybrid cloud"), ("c", "Private cloud on AWS (e.g., Outposts)"), ("d", "Multi-tenant SaaS only")], ["c"],
     "Private/hybrid options include VPC-only workloads and AWS Outposts for on-premises AWS infrastructure.",
     [("Cloud Deployment Models", "https://aws.amazon.com/types-of-cloud-computing/")]),
    ("cloud-concepts", "multiple-response",
     "Which are advantages of cloud computing? (Select TWO.)",
     [("a", "Trade capital expense for variable expense"), ("b", "Eliminate all operational staff"),
      ("c", "Stop guessing capacity"), ("d", "Guarantee zero downtime"), ("e", "Go global in minutes")], ["a", "c", "e"],
     "Common advantages include variable expense, elasticity, and global reach; cloud does not eliminate ops or guarantee zero downtime.",
     [("Six Advantages of Cloud", "https://docs.aws.amazon.com/whitepapers/latest/aws-overview/six-advantages-of-cloud-computing.html")]),
    ("cloud-concepts", "multiple-choice",
     "Which service provides a central view to manage billing, support, and IAM across AWS accounts?",
     [("a", "AWS Organizations"), ("b", "AWS Control Tower"), ("c", "AWS Management Console"), ("d", "AWS Budgets")], ["a"],
     "AWS Organizations helps consolidate billing and apply policies across multiple accounts.",
     [("AWS Organizations", "https://docs.aws.amazon.com/organizations/latest/userguide/orgs_introduction.html")]),
    ("cloud-concepts", "multiple-choice",
     "The AWS Cloud Adoption Framework (CAF) is primarily used to help organizations with:",
     [("a", "Hardware repair procedures"), ("b", "Structured cloud transformation across business capabilities"),
      ("c", "Subnet sizing only"), ("d", "Certificate pinning")], ["b"],
     "CAF provides guidance across perspectives such as business, people, governance, platform, security, and operations.",
     [("AWS CAF", "https://aws.amazon.com/cloud-adoption-framework/")]),
    ("cloud-concepts", "multiple-choice",
     "Which statement best describes elasticity in AWS?",
     [("a", "Resources are fixed at purchase time"), ("b", "Resources scale up or down to match demand"),
      ("c", "Data is encrypted at rest only"), ("d", "Users must manage physical servers")], ["b"],
     "Elasticity is the ability to acquire resources as needed and release them when no longer needed.",
     [("AWS Overview Whitepaper", "https://docs.aws.amazon.com/whitepapers/latest/aws-overview/")]),
    ("cloud-concepts", "multiple-choice",
     "Edge locations are used primarily by which service to cache content closer to users?",
     [("a", "Amazon Route 53"), ("b", "Amazon CloudFront"), ("c", "AWS Direct Connect"), ("d", "Amazon VPC")], ["b"],
     "Amazon CloudFront is a content delivery network (CDN) that uses edge locations.",
     [("Amazon CloudFront", "https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/Introduction.html")]),
    ("cloud-concepts", "multiple-choice",
     "Which pillar of the Well-Architected Framework focuses on running and monitoring systems to deliver business value?",
     [("a", "Reliability"), ("b", "Operational Excellence"), ("c", "Sustainability"), ("d", "Performance Efficiency")], ["b"],
     "Operational Excellence covers operations in production and improvement of procedures.",
     [("Operational Excellence pillar", "https://docs.aws.amazon.com/wellarchitected/latest/operational-excellence-pillar/welcome.html")]),
    ("cloud-concepts", "multiple-choice",
     "A startup needs to run a web application with minimal server management. Which compute option is most appropriate at a high level?",
     [("a", "Amazon EC2 only"), ("b", "AWS Lambda or managed containers"), ("c", "On-premises mainframe"), ("d", "Bare metal racks")], ["b"],
     "Serverless (Lambda) and managed services reduce undifferentiated heavy lifting for new workloads.",
     [("AWS Compute", "https://aws.amazon.com/products/compute/")]),
    ("cloud-concepts", "multiple-choice",
     "Which AWS service helps you create and manage AWS accounts with governance guardrails?",
     [("a", "AWS Control Tower"), ("b", "Amazon S3"), ("c", "Amazon RDS"), ("d", "AWS Snowball")], ["a"],
     "Control Tower automates setup of a multi-account environment with best-practice blueprints.",
     [("AWS Control Tower", "https://docs.aws.amazon.com/controltower/latest/userguide/what-is-control-tower.html")]),
    ("cloud-concepts", "multiple-choice",
     "High availability in AWS is best achieved by:",
     [("a", "Deploying in a single Availability Zone"), ("b", "Designing across multiple Availability Zones"),
      ("c", "Using one large instance"), ("d", "Disabling auto scaling")], ["b"],
     "Multi-AZ designs protect against data center-level failures within a Region.",
     [("Reliability pillar", "https://docs.aws.amazon.com/wellarchitected/latest/reliability-pillar/welcome.html")]),
    ("cloud-concepts", "multiple-choice",
     "Which tool provides a customized view of AWS service health and alerts for your account?",
     [("a", "AWS Personal Health Dashboard"), ("b", "AWS Artifact"), ("c", "AWS Trusted Advisor"), ("d", "AWS Config")], ["a"],
     "Personal Health Dashboard alerts you to events that may affect your resources.",
     [("AWS Health", "https://docs.aws.amazon.com/health/latest/ug/what-is-aws-health.html")]),
    ("cloud-concepts", "multiple-choice",
     "The AWS Acceptable Use Policy describes:",
     [("a", "How to size EC2 instances"), ("b", "Prohibited uses of AWS services"), ("c", "S3 storage classes"), ("d", "VPC CIDR blocks")], ["b"],
     "Acceptable Use Policy defines restrictions on use of AWS services.",
     [("AWS Acceptable Use Policy", "https://aws.amazon.com/aup/")]),
    ("security-compliance", "multiple-choice",
     "Under the AWS shared responsibility model, which task is the customer's responsibility?",
     [("a", "Patching the hypervisor"), ("b", "Configuring security groups on EC2"), ("c", "Physical data center security"), ("d", "Managing hardware firmware")], ["b"],
     "Customers are responsible for security IN the cloud, including guest OS and firewall configuration.",
     [("Shared Responsibility", "https://aws.amazon.com/compliance/shared-responsibility-model/")]),
    ("security-compliance", "multiple-choice",
     "Which IAM feature allows temporary security credentials for users and roles?",
     [("a", "IAM Access Analyzer"), ("b", "AWS STS (Security Token Service)"), ("c", "AWS KMS"), ("d", "Amazon GuardDuty")], ["b"],
     "STS issues temporary credentials used by roles, federation, and MFA sessions.",
     [("AWS STS", "https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_temp.html")]),
    ("security-compliance", "multiple-choice",
     "What does the principle of least privilege recommend?",
     [("a", "Grant administrators all permissions by default"), ("b", "Grant only permissions required to perform a task"),
      ("c", "Share root account keys across teams"), ("d", "Disable logging")], ["b"],
     "Least privilege limits access to the minimum needed, reducing blast radius.",
     [("IAM best practices", "https://docs.aws.amazon.com/IAM/latest/UserGuide/best-practices.html")]),
    ("security-compliance", "multiple-choice",
     "Which service provides centralized governance and compliance reports for AWS agreements and certifications?",
     [("a", "AWS Artifact"), ("b", "Amazon Inspector"), ("c", "AWS Shield"), ("d", "Amazon Macie")], ["a"],
     "AWS Artifact provides on-demand access to AWS compliance reports.",
     [("AWS Artifact", "https://docs.aws.amazon.com/artifact/latest/ug/what-is-aws-artifact.html")]),
    ("security-compliance", "multiple-choice",
     "Multi-factor authentication (MFA) for the AWS account root user is recommended because:",
     [("a", "It reduces S3 storage cost"), ("b", "It adds a layer of protection for the most privileged account"),
      ("c", "It replaces the need for IAM"), ("d", "It encrypts EBS volumes automatically")], ["b"],
     "Root user has full account access; MFA helps protect against credential compromise.",
     [("Securing root user", "https://docs.aws.amazon.com/IAM/latest/UserGuide/id_root-user.html")]),
    ("security-compliance", "multiple-response",
     "Which are AWS services or features that help detect security threats? (Select TWO.)",
     [("a", "Amazon GuardDuty"), ("b", "Amazon S3 Glacier"), ("c", "AWS Security Hub"), ("d", "Amazon Aurora"), ("e", "AWS Batch")], ["a", "c"],
     "GuardDuty finds malicious activity; Security Hub aggregates security findings.",
     [("Amazon GuardDuty", "https://docs.aws.amazon.com/guardduty/latest/ug/what-is-guardduty.html")]),
    ("security-compliance", "multiple-choice",
     "AWS KMS is primarily used for:",
     [("a", "Creating and managing encryption keys"), ("b", "DNS routing"), ("c", "Load balancing"), ("d", "Log shipping only")], ["a"],
     "AWS Key Management Service manages cryptographic keys for AWS and your applications.",
     [("AWS KMS", "https://docs.aws.amazon.com/kms/latest/developerguide/overview.html")]),
    ("security-compliance", "multiple-choice",
     "Which network feature acts as a virtual firewall at the instance level in a VPC?",
     [("a", "Network ACL"), ("b", "Security group"), ("c", "Route table"), ("d", "Internet gateway")], ["b"],
     "Security groups are stateful firewalls for EC2 instances and ENIs.",
     [("Security groups", "https://docs.aws.amazon.com/vpc/latest/userguide/vpc-security-groups.html")]),
    ("security-compliance", "multiple-choice",
     "AWS CloudTrail is used to:",
     [("a", "Store static website assets"), ("b", "Log API activity across your AWS account"), ("c", "Run containers"), ("d", "Create AMIs")], ["b"],
     "CloudTrail records AWS API calls for auditing and governance.",
     [("AWS CloudTrail", "https://docs.aws.amazon.com/awscloudtrail/latest/userguide/cloudtrail-user-guide.html")]),
    ("security-compliance", "multiple-choice",
     "Which service helps you analyze, investigate, and identify the root cause of security findings?",
     [("a", "AWS Security Hub"), ("b", "Amazon Detective"), ("c", "AWS WAF"), ("d", "Amazon Connect")], ["b"],
     "Amazon Detective visualizes security data to investigate potential issues.",
     [("Amazon Detective", "https://docs.aws.amazon.com/detective/latest/userguide/what-is-detective.html")]),
    ("security-compliance", "multiple-choice",
     "Encryption of data at rest on Amazon S3 is often implemented using:",
     [("a", "S3 server-side encryption with KMS or S3-managed keys"), ("b", "Route 53 health checks"), ("c", "Elastic IPs"), ("d", "Placement groups")], ["a"],
     "S3 supports SSE-S3, SSE-KMS, and client-side encryption options.",
     [("S3 encryption", "https://docs.aws.amazon.com/AmazonS3/latest/userguide/UsingEncryption.html")]),
    ("security-compliance", "multiple-choice",
     "An IAM policy is:",
     [("a", "A document defining permissions"), ("b", "A physical security badge"), ("c", "A type of EC2 instance"), ("d", "A billing invoice")], ["a"],
     "Policies are JSON documents that define what actions are allowed or denied.",
     [("IAM policies", "https://docs.aws.amazon.com/IAM/latest/UserGuide/access_policies.html")]),
    ("security-compliance", "multiple-choice",
     "AWS Shield Standard provides:",
     [("a", "DDoS protection for all AWS customers at no additional charge"), ("b", "Only S3 lifecycle management"), ("c", "VPN tunnels"), ("d", "Database backups")], ["a"],
     "Shield Standard automatically protects against common network and transport layer DDoS.",
     [("AWS Shield", "https://docs.aws.amazon.com/waf/latest/developerguide/shield-chapter.html")]),
    ("security-compliance", "multiple-choice",
     "Which compliance concept means AWS undergoes third-party audits for standards such as ISO and SOC?",
     [("a", "Customer patch management"), ("b", "AWS compliance programs and attestations"), ("c", "EC2 Auto Scaling"), ("d", "S3 Transfer Acceleration")], ["b"],
     "AWS maintains many compliance certifications customers can inherit via shared responsibility.",
     [("AWS Compliance", "https://aws.amazon.com/compliance/programs/")]),
    ("security-compliance", "multiple-choice",
     "Federation with corporate identity providers commonly uses:",
     [("a", "AWS IAM Identity Center (SSO)"), ("b", "Amazon EBS snapshots only"), ("c", "Snowmobile"), ("d", "Amazon Lightsail databases only")], ["a"],
     "IAM Identity Center enables SSO and federation with external identity sources.",
     [("IAM Identity Center", "https://docs.aws.amazon.com/singlesignon/latest/userguide/what-is.html")]),
    ("security-compliance", "multiple-choice",
     "Network ACLs in a VPC are:",
     [("a", "Stateless filters at the subnet level"), ("b", "Stateful instance firewalls"), ("c", "DNS resolvers"), ("d", "S3 policies")], ["a"],
     "NACLs provide optional stateless allow/deny rules for subnets.",
     [("Network ACLs", "https://docs.aws.amazon.com/vpc/latest/userguide/vpc-network-acls.html")]),
    ("security-compliance", "multiple-choice",
     "Which AWS service provides DDoS protection and web application firewall capabilities?",
     [("a", "AWS WAF and AWS Shield"), ("b", "Amazon RDS"), ("c", "AWS Glue"), ("d", "Amazon EFS")], ["a"],
     "AWS WAF filters HTTP/S requests; Shield provides DDoS mitigation.",
     [("AWS WAF", "https://docs.aws.amazon.com/waf/latest/developerguide/waf-chapter.html")]),
    ("technology-services", "multiple-choice",
     "Which service provides resizable compute capacity in the cloud?",
     [("a", "Amazon EC2"), ("b", "Amazon S3"), ("c", "Amazon Route 53"), ("d", "AWS CloudFormation")], ["a"],
     "Amazon Elastic Compute Cloud (EC2) provides virtual servers.",
     [("Amazon EC2", "https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/concepts.html")]),
    ("technology-services", "multiple-choice",
     "Amazon S3 is best described as:",
     [("a", "Object storage"), ("b", "Block storage for EC2 only"), ("c", "Relational database"), ("d", "Message queue")], ["a"],
     "S3 stores objects in buckets with high durability and scalability.",
     [("Amazon S3", "https://docs.aws.amazon.com/AmazonS3/latest/userguide/Welcome.html")]),
    ("technology-services", "multiple-choice",
     "Which database service is fully managed and serverless with automatic scaling?",
     [("a", "Amazon DynamoDB"), ("b", "Self-managed MySQL on a laptop"), ("c", "Tape backup"), ("d", "FTP server")], ["a"],
     "DynamoDB is a managed NoSQL database with serverless capacity modes.",
     [("Amazon DynamoDB", "https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Introduction.html")]),
    ("technology-services", "multiple-choice",
     "Amazon RDS is used for:",
     [("a", "Managed relational databases"), ("b", "Object archival only"), ("c", "CDN caching"), ("d", "DNS registration")], ["a"],
     "RDS manages databases such as MySQL, PostgreSQL, and SQL Server.",
     [("Amazon RDS", "https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/Welcome.html")]),
    ("technology-services", "multiple-choice",
     "Which service decouples application components using message queues?",
     [("a", "Amazon SQS"), ("b", "Amazon EBS"), ("c", "AWS Snowcone"), ("d", "Amazon Lightsail snapshots")], ["a"],
     "Amazon Simple Queue Service (SQS) enables asynchronous messaging.",
     [("Amazon SQS", "https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/welcome.html")]),
    ("technology-services", "multiple-choice",
     "AWS Lambda runs code:",
     [("a", "Without provisioning servers, in response to events"), ("b", "Only on physical mainframes"), ("c", "Only inside VPC by default with no config"), ("d", "Only for DNS")], ["a"],
     "Lambda is serverless compute that executes code on demand.",
     [("AWS Lambda", "https://docs.aws.amazon.com/lambda/latest/dg/welcome.html")]),
    ("technology-services", "multiple-choice",
     "Amazon VPC allows you to:",
     [("a", "Provision an isolated network in AWS"), ("b", "Ship hardware to AWS"), ("c", "Replace IAM"), ("d", "Manage domain registration only")], ["a"],
     "VPC lets you define private subnets, routing, and connectivity.",
     [("Amazon VPC", "https://docs.aws.amazon.com/vpc/latest/userguide/what-is-amazon-vpc.html")]),
    ("technology-services", "multiple-choice",
     "Which service is a managed Kubernetes control plane?",
     [("a", "Amazon EKS"), ("b", "Amazon SNS"), ("c", "AWS Step Functions"), ("d", "Amazon Cognito")], ["a"],
     "Amazon Elastic Kubernetes Service (EKS) runs Kubernetes on AWS.",
     [("Amazon EKS", "https://docs.aws.amazon.com/eks/latest/userguide/what-is-eks.html")]),
    ("technology-services", "multiple-choice",
     "Amazon CloudWatch is primarily used for:",
     [("a", "Monitoring metrics and logs"), ("b", "Domain registration"), ("c", "Data warehouse ETL only"), ("d", "Hardware procurement")], ["a"],
     "CloudWatch collects metrics, logs, and alarms for AWS resources.",
     [("Amazon CloudWatch", "https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/WhatIsCloudWatch.html")]),
    ("technology-services", "multiple-choice",
     "Which storage service provides block volumes for EC2 instances?",
     [("a", "Amazon EBS"), ("b", "Amazon S3"), ("c", "Amazon Glacier Instant Retrieval only as block"), ("d", "AWS DataSync")], ["a"],
     "Amazon Elastic Block Store attaches persistent block storage to EC2.",
     [("Amazon EBS", "https://docs.aws.amazon.com/ebs/latest/userguide/what-is-ebs.html")]),
    ("technology-services", "multiple-response",
     "Which are AWS compute services? (Select TWO.)",
     [("a", "AWS Fargate"), ("b", "Amazon Redshift"), ("c", "Amazon EC2"), ("d", "Amazon Macie"), ("e", "AWS Artifact")], ["a", "c"],
     "EC2 and Fargate (serverless containers) are compute options; Redshift is analytics.",
     [("AWS Compute", "https://aws.amazon.com/products/compute/")]),
    ("technology-services", "multiple-choice",
     "Amazon Route 53 provides:",
     [("a", "DNS and domain registration services"), ("b", "GPU clusters only"), ("c", "Tape libraries"), ("d", "Email marketing")], ["a"],
     "Route 53 is a scalable DNS web service.",
     [("Route 53", "https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/Welcome.html")]),
    ("technology-services", "multiple-choice",
     "AWS CloudFormation helps you:",
     [("a", "Model and provision infrastructure as code"), ("b", "Replace all security controls"), ("c", "Ship Snowball devices only"), ("d", "Manage payroll")], ["a"],
     "CloudFormation templates describe AWS resources for repeatable deployments.",
     [("AWS CloudFormation", "https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/Welcome.html")]),
    ("technology-services", "multiple-choice",
     "Amazon API Gateway is used to:",
     [("a", "Create, publish, and manage APIs"), ("b", "Store Glacier archives only"), ("c", "Run Hadoop exclusively"), ("d", "Replace VPC")], ["a"],
     "API Gateway handles API traffic for REST, HTTP, and WebSocket APIs.",
     [("Amazon API Gateway", "https://docs.aws.amazon.com/apigateway/latest/developerguide/welcome.html")]),
    ("technology-services", "multiple-choice",
     "Which service is best for breaking a monolith into microservices with event-driven communication?",
     [("a", "Amazon EventBridge"), ("b", "Amazon S3 Glacier Deep Archive only"), ("c", "AWS Snowmobile"), ("d", "Amazon WorkSpaces")], ["a"],
     "EventBridge is a serverless event bus for connecting application components.",
     [("Amazon EventBridge", "https://docs.aws.amazon.com/eventbridge/latest/userguide/eb-what-is.html")]),
    ("technology-services", "multiple-choice",
     "Amazon Aurora is:",
     [("a", "A MySQL and PostgreSQL-compatible relational database"), ("b", "An object CDN"), ("c", "A VPN appliance"), ("d", "A compliance report")], ["a"],
     "Aurora is a managed relational database with high performance and availability.",
     [("Amazon Aurora", "https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/CHAP_AuroraOverview.html")]),
    ("technology-services", "multiple-choice",
     "AWS Elastic Beanstalk is designed to:",
     [("a", "Deploy and scale web applications with minimal infrastructure decisions"), ("b", "Replace S3"), ("c", "Audit IAM only"), ("d", "Manage domain WHOIS")], ["a"],
     "Elastic Beanstalk handles capacity provisioning, load balancing, and scaling for apps.",
     [("AWS Elastic Beanstalk", "https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/Welcome.html")]),
    ("billing-pricing-support", "multiple-choice",
     "Which pricing model offers the largest discount for steady-state workloads with a 1- or 3-year commitment?",
     [("a", "On-Demand"), ("b", "Reserved Instances / Savings Plans"), ("c", "Spot Instances without interruption tolerance"), ("d", "Data transfer out only")], ["b"],
     "Reserved capacity and Savings Plans reduce cost for predictable usage.",
     [("Reserved Instances", "https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-reserved-instances.html")]),
    ("billing-pricing-support", "multiple-choice",
     "AWS Cost Explorer allows you to:",
     [("a", "Visualize and analyze AWS spending over time"), ("b", "Patch Linux kernels"), ("c", "Create VPC peering"), ("d", "Register domains")], ["a"],
     "Cost Explorer provides charts and forecasts for cost and usage.",
     [("Cost Explorer", "https://docs.aws.amazon.com/cost-management/latest/userguide/ce-what-is.html")]),
    ("billing-pricing-support", "multiple-choice",
     "Which support plan includes 24/7 access to Cloud Support Engineers via phone and chat?",
     [("a", "Basic"), ("b", "Developer"), ("c", "Business or Enterprise On-Ramp/Enterprise")], ["c"],
     "Business and Enterprise plans include 24/7 technical support by phone and chat.",
     [("AWS Support Plans", "https://aws.amazon.com/premiumsupport/")]),
    ("billing-pricing-support", "multiple-choice",
     "The AWS Free Tier:",
     [("a", "Offers limited free usage for new and eligible services under stated terms"), ("b", "Makes all AWS usage free forever"), ("c", "Applies only to Enterprise support"), ("d", "Replaces billing accounts")], ["a"],
     "Free Tier has time and usage limits; always check current terms per service.",
     [("AWS Free Tier", "https://aws.amazon.com/free/")]),
    ("billing-pricing-support", "multiple-choice",
     "Consolidated billing in AWS Organizations:",
     [("a", "Combines usage across accounts for volume pricing benefits"), ("b", "Eliminates the need for IAM"), ("c", "Removes all data transfer charges"), ("d", "Is only for GovCloud")], ["a"],
     "Consolidated billing aggregates charges and can share Reserved Instance benefits.",
     [("Consolidated billing", "https://docs.aws.amazon.com/awsaccountbilling/latest/aboutv2/consolidated-billing.html")]),
    ("billing-pricing-support", "multiple-choice",
     "AWS Budgets can:",
     [("a", "Set custom cost and usage thresholds with alerts"), ("b", "Automatically delete all S3 buckets"), ("c", "Replace CloudTrail"), ("d", "Provision Outposts")], ["a"],
     "Budgets helps track spend against plans you define.",
     [("AWS Budgets", "https://docs.aws.amazon.com/cost-management/latest/userguide/budgets-managing-costs.html")]),
    ("billing-pricing-support", "multiple-choice",
     "Spot Instances are appropriate when:",
     [("a", "Workloads can tolerate interruption and want lowest price"), ("b", "You need guaranteed capacity for 3 years"), ("c", "You cannot checkpoint work"), ("d", "You require dedicated hosts only")], ["a"],
     "Spot uses spare capacity at a discount; instances can be reclaimed with notice.",
     [("Spot Instances", "https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/using-spot-instances.html")]),
    ("billing-pricing-support", "multiple-choice",
     "Which document provides estimates of service pricing for planning?",
     [("a", "AWS Pricing Calculator"), ("b", "IAM policy simulator only"), ("c", "VPC Flow Logs"), ("d", "AWS Artifact compliance PDFs only")], ["a"],
     "AWS Pricing Calculator (formerly Simple Monthly Calculator) estimates costs.",
     [("AWS Pricing Calculator", "https://calculator.aws/")]),
    ("billing-pricing-support", "multiple-choice",
     "AWS Trusted Advisor provides:",
     [("a", "Best-practice recommendations across cost, performance, security, and fault tolerance"), ("b", "Physical data center tours"), ("c", "Unlimited free Enterprise support"), ("d", "Domain WHOIS privacy")], ["a"],
     "Trusted Advisor inspects your environment and suggests improvements.",
     [("AWS Trusted Advisor", "https://docs.aws.amazon.com/awssupport/latest/user/trusted-advisor.html")]),
    ("billing-pricing-support", "multiple-choice",
     "Which is TRUE about AWS Support Basic plan?",
     [("a", "It is included for all AWS customers at no additional charge"), ("b", "It includes 15-minute response for production down"), ("c", "It includes TAM assignment"), ("d", "It includes AWS Managed Services")], ["a"],
     "Basic support is free and includes customer service and documentation access.",
     [("Support plans comparison", "https://aws.amazon.com/premiumsupport/")]),
    ("billing-pricing-support", "multiple-choice",
     "AWS Cost and Usage Report (CUR) delivers:",
     [("a", "Detailed line-item billing data to an S3 bucket you own"), ("b", "EC2 AMI catalogs"), ("c", "Route 53 health checks only"), ("d", "IAM user passwords")], ["a"],
     "CUR provides comprehensive billing data for analysis and allocation.",
     [("Cost and Usage Reports", "https://docs.aws.amazon.com/cur/latest/userguide/what-is-cur.html")]),
    ("billing-pricing-support", "multiple-choice",
     "Moving data OUT of AWS to the internet generally:",
     [("a", "May incur data transfer out charges"), ("b", "Is always free unlimited"), ("c", "Costs more than data transfer in"), ("d", "Is charged per IAM user")], ["a"],
     "Data transfer pricing varies by service and direction; outbound to internet is often charged.",
     [("AWS data transfer pricing", "https://aws.amazon.com/ec2/pricing/on-demand/#Data_Transfer")]),
    # Pad to 65 with additional varied questions
    ("technology-services", "multiple-choice",
     "Amazon SNS is used for:",
     [("a", "Pub/sub notifications and messaging"), ("b", "Block storage"), ("c", "VPN only"), ("d", "Code repositories")], ["a"],
     "Simple Notification Service publishes messages to subscribers and other services.",
     [("Amazon SNS", "https://docs.aws.amazon.com/sns/latest/dg/welcome.html")]),
    ("security-compliance", "multiple-choice",
     "AWS Config is used to:",
     [("a", "Assess, audit, and evaluate configurations of AWS resources"), ("b", "Register domains"), ("c", "Run SQL queries on S3 only"), ("d", "Replace CloudFront")], ["a"],
     "AWS Config tracks resource configuration changes over time.",
     [("AWS Config", "https://docs.aws.amazon.com/config/latest/developerguide/WhatIsConfig.html")]),
    ("cloud-concepts", "multiple-choice",
     "A Region in AWS is:",
     [("a", "A separate geographic area containing multiple Availability Zones"), ("b", "A single rack in one building only"), ("c", "An IAM user group"), ("d", "A billing report")], ["a"],
     "Regions are independent geographic areas for deployment and compliance.",
     [("Regions and AZs", "https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/Concepts.RegionsAndAvailabilityZones.html")]),
    ("technology-services", "multiple-choice",
     "Amazon Athena allows you to:",
     [("a", "Query data in S3 using standard SQL"), ("b", "Manage EC2 Auto Scaling only"), ("c", "Create IAM roles"), ("d", "Ship Snowball Edge")], ["a"],
     "Athena is serverless interactive query service for S3 data.",
     [("Amazon Athena", "https://docs.aws.amazon.com/athena/latest/ug/what-is.html")]),
    ("billing-pricing-support", "multiple-choice",
     "Savings Plans apply to:",
     [("a", "Compute usage in exchange for a commitment to a consistent amount ($/hour)"), ("b", "Only S3 Glacier"), ("c", "Only Route 53 domains"), ("d", "Support plan fees only")], ["a"],
     "Savings Plans offer lower prices on compute in return for a one- or three-year commitment.",
     [("Savings Plans", "https://docs.aws.amazon.com/savingsplans/latest/userguide/what-is-savings-plans.html")]),
]

# Minimum questions per domain needed for one CLF-C02-weighted exam (65 questions).
EXAM_DOMAIN_MIN = {
    "cloud-concepts": 16,
    "security-compliance": 20,
    "technology-services": 22,
    "billing-pricing-support": 8,
}

ALL_RAW = RAW + EXTENDED


def build_questions():
    questions = []
    for i, row in enumerate(ALL_RAW, start=1):
        domain, qtype, text, opts, correct, explanation, docs = row
        questions.append({
            "id": f"clf-q{i:03d}",
            "domain": domain,
            "type": qtype,
            "text": text,
            "options": [{"id": oid, "text": otext} for oid, otext in opts],
            "correct": correct,
            "explanation": explanation,
            "docs": [{"title": t, "url": u} for t, u in docs],
        })
    return questions


def validate_pool(questions):
    by_domain = {}
    for q in questions:
        by_domain[q["domain"]] = by_domain.get(q["domain"], 0) + 1
    errors = []
    for domain_id, minimum in EXAM_DOMAIN_MIN.items():
        count = by_domain.get(domain_id, 0)
        if count < minimum:
            errors.append(f"{domain_id}: have {count}, need {minimum} for one weighted exam")
    if errors:
        raise SystemExit("Question pool too small per CLF-C02 domain:\n" + "\n".join(errors))


def main():
    questions = build_questions()
    validate_pool(questions)

    payload = {
        "id": "cloud-practitioner",
        "name": "AWS Certified Cloud Practitioner",
        "code": "CLF-C02",
        "vendor": "aws",
        "exam": {
            "totalQuestions": 65,
            "scoredQuestions": 50,
            "timeLimitMinutes": 90,
            "passingScore": 700,
            "maxScore": 1000,
            "selectionMode": "weighted-random",
        },
        "domains": DOMAINS,
        "questions": questions,
    }
    EXAMS_DIR.mkdir(parents=True, exist_ok=True)
    OUT.write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")
    by_domain = {}
    for q in questions:
        by_domain[q["domain"]] = by_domain.get(q["domain"], 0) + 1
    print(f"Wrote {len(questions)} questions to {OUT}")
    for d in DOMAINS:
        print(f"  {d['id']}: {by_domain.get(d['id'], 0)} (exam uses ~{EXAM_DOMAIN_MIN[d['id']]} per attempt)")

    import importlib.util

    index_script = ROOT / "scripts" / "build-exams-index.py"
    spec = importlib.util.spec_from_file_location("build_exams_index", index_script)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)  # type: ignore[union-attr]
    print()
    module.main()

if __name__ == "__main__":
    main()
